
// autogenerated tests for w3strings (require modBase-Utils)
// language: en

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114471000) == "Aard Shatter", "w3string.byId: 2114471000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471001) == "Shatter humans with broken poise", "w3string.byId: 2114471001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471002) == "   ...only below this health %", "w3string.byId: 2114471002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471003) == "Shatter anything Aard kills", "w3string.byId: 2114471003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471004) == "   ...including humans", "w3string.byId: 2114471004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471005) == "Slow motion chance on shatter", "w3string.byId: 2114471005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471006) == "   ...strength (lower = stronger)", "w3string.byId: 2114471006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471007) == "   ...duration, sec", "w3string.byId: 2114471007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471008) == "Finisher variety: 0 off, 1 vanilla, 2 max", "w3string.byId: 2114471008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471009) == "   ...chance curve scale (100 = one to one)", "w3string.byId: 2114471009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471010) == "Igni shatters humans too", "w3string.byId: 2114471010")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471011) == "Shatter anything Igni kills", "w3string.byId: 2114471011")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471012) == "Fix: Eruption disables finishers", "w3string.byId: 2114471012")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471013) == "Dismember armoured humans", "w3string.byId: 2114471013")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471014) == "   ...chance for armoured", "w3string.byId: 2114471014")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("ash_menu") == "Aard Shatter", "w3string.byKey: ash_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_humanpoise") == "Shatter humans with broken poise", "w3string.byKey: ash_humanpoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_humanhp") == "   ...only below this health %", "w3string.byKey: ash_humanhp")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_killshatter") == "Shatter anything Aard kills", "w3string.byKey: ash_killshatter")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_killshatterhumans") == "   ...including humans", "w3string.byKey: ash_killshatterhumans")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_slomochance") == "Slow motion chance on shatter", "w3string.byKey: ash_slomochance")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_slomoscale") == "   ...strength (lower = stronger)", "w3string.byKey: ash_slomoscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_slomotime") == "   ...duration, sec", "w3string.byKey: ash_slomotime")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_finvariety") == "Finisher variety: 0 off, 1 vanilla, 2 max", "w3string.byKey: ash_finvariety")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_shatterscale") == "   ...chance curve scale (100 = one to one)", "w3string.byKey: ash_shatterscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_ignipoise") == "Igni shatters humans too", "w3string.byKey: ash_ignipoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_ignikill") == "Shatter anything Igni kills", "w3string.byKey: ash_ignikill")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_fixignilatch") == "Fix: Eruption disables finishers", "w3string.byKey: ash_fixignilatch")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_armordism") == "Dismember armoured humans", "w3string.byKey: ash_armordism")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_armorchance") == "   ...chance for armoured", "w3string.byKey: ash_armorchance")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
