
// autogenerated tests for w3strings (require modBase-Utils)
// language: ru

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114471000) == "Разрыв Аардом", "w3string.byId: 2114471000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471001) == "Разрывать людей со сбитой стойкой", "w3string.byId: 2114471001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471002) == "   ...только ниже этого % здоровья", "w3string.byId: 2114471002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471003) == "Разрывать всех, кого добил Аард", "w3string.byId: 2114471003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471004) == "   ...включая людей", "w3string.byId: 2114471004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471005) == "Шанс замедления времени при разрыве", "w3string.byId: 2114471005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471006) == "   ...сила замедления (меньше = сильнее)", "w3string.byId: 2114471006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471007) == "   ...длительность, сек", "w3string.byId: 2114471007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471008) == "Разнообразие добиваний: 0 выкл, 1 ваниль, 2 макс", "w3string.byId: 2114471008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471009) == "   ...крутизна кривой шанса (100 = один к одному)", "w3string.byId: 2114471009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471010) == "Разрывать людей Игни (та же логика)", "w3string.byId: 2114471010")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471011) == "Разрывать всех, кого добил Игни", "w3string.byId: 2114471011")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471012) == "Чинить баг: Eruption убивает добивания", "w3string.byId: 2114471012")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471013) == "Расчленять бронированных людей", "w3string.byId: 2114471013")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471014) == "   ...шанс для бронированных", "w3string.byId: 2114471014")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("ash_menu") == "Разрыв Аардом", "w3string.byKey: ash_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_humanpoise") == "Разрывать людей со сбитой стойкой", "w3string.byKey: ash_humanpoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_humanhp") == "   ...только ниже этого % здоровья", "w3string.byKey: ash_humanhp")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_killshatter") == "Разрывать всех, кого добил Аард", "w3string.byKey: ash_killshatter")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_killshatterhumans") == "   ...включая людей", "w3string.byKey: ash_killshatterhumans")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_slomochance") == "Шанс замедления времени при разрыве", "w3string.byKey: ash_slomochance")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_slomoscale") == "   ...сила замедления (меньше = сильнее)", "w3string.byKey: ash_slomoscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_slomotime") == "   ...длительность, сек", "w3string.byKey: ash_slomotime")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_finvariety") == "Разнообразие добиваний: 0 выкл, 1 ваниль, 2 макс", "w3string.byKey: ash_finvariety")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_shatterscale") == "   ...крутизна кривой шанса (100 = один к одному)", "w3string.byKey: ash_shatterscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_ignipoise") == "Разрывать людей Игни (та же логика)", "w3string.byKey: ash_ignipoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_ignikill") == "Разрывать всех, кого добил Игни", "w3string.byKey: ash_ignikill")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_fixignilatch") == "Чинить баг: Eruption убивает добивания", "w3string.byKey: ash_fixignilatch")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_armordism") == "Расчленять бронированных людей", "w3string.byKey: ash_armordism")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ash_armorchance") == "   ...шанс для бронированных", "w3string.byKey: ash_armorchance")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
