
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114472000) == "누구든 절단", "w3string.byId: 2114472000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472001) == "갑옷 입은 인간도 절단", "w3string.byId: 2114472001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472002) == "   ...확률", "w3string.byId: 2114472002")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("dsma_menu") == "누구든 절단", "w3string.byKey: dsma_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_armordism") == "갑옷 입은 인간도 절단", "w3string.byKey: dsma_armordism")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_armorchance") == "   ...확률", "w3string.byKey: dsma_armorchance")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
