
// autogenerated tests for w3strings (require modBase-Utils)
// language: cz

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114472000) == "Rozsekat Kohokoli", "w3string.byId: 2114472000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472001) == "Rozsekat obrněné lidi", "w3string.byId: 2114472001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472002) == "   ...šance", "w3string.byId: 2114472002")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("dsma_menu") == "Rozsekat Kohokoli", "w3string.byKey: dsma_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_armordism") == "Rozsekat obrněné lidi", "w3string.byKey: dsma_armordism")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_armorchance") == "   ...šance", "w3string.byKey: dsma_armorchance")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
