
// autogenerated tests for w3strings (require modBase-Utils)
// language: cz

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114473000) == "Rozmanitost Dobíjení", "w3string.byId: 2114473000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114473001) == "Rozmanitost: 0 W3EE, 1 vanilla, 2 max", "w3string.byId: 2114473001")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("fvar_menu") == "Rozmanitost Dobíjení", "w3string.byKey: fvar_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("fvar_mode") == "Rozmanitost: 0 W3EE, 1 vanilla, 2 max", "w3string.byKey: fvar_mode")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
