
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114474000) == "메타모르포시스 선택", "w3string.byId: 2114474000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114474001) == "돌연변이 화면에서 돌연변이 선택", "w3string.byId: 2114474001")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("mmpk_menu") == "메타모르포시스 선택", "w3string.byKey: mmpk_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mmpk_enabled") == "돌연변이 화면에서 돌연변이 선택", "w3string.byKey: mmpk_enabled")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
