
// autogenerated tests for w3strings (require modBase-Utils)
// language: it

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114474000) == "Selettore Metamorfosi", "w3string.byId: 2114474000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114474001) == "Scegli le mutazioni nella schermata mutazioni", "w3string.byId: 2114474001")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("mmpk_menu") == "Selettore Metamorfosi", "w3string.byKey: mmpk_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mmpk_enabled") == "Scegli le mutazioni nella schermata mutazioni", "w3string.byKey: mmpk_enabled")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
