
// autogenerated tests for w3strings (require modBase-Utils)
// language: en

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114474000) == "Metamorphosis Picker", "w3string.byId: 2114474000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114474001) == "Pick mutations in the mutation screen", "w3string.byId: 2114474001")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("mmpk_menu") == "Metamorphosis Picker", "w3string.byKey: mmpk_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mmpk_enabled") == "Pick mutations in the mutation screen", "w3string.byKey: mmpk_enabled")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
