
// autogenerated tests for w3strings (require modBase-Utils)
// language: hu

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114471000) == "Jelrobbantás", "w3string.byId: 2114471000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471001) == "Megtört egyensúlyú emberek szétszaggatása", "w3string.byId: 2114471001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471002) == "   ...csak ezen életerő % alatt", "w3string.byId: 2114471002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471003) == "   ...esélygörbe (100 = egy az egyhez)", "w3string.byId: 2114471003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471004) == "Szaggasd szét, amit az Aard megöl", "w3string.byId: 2114471004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471005) == "   ...embereket is", "w3string.byId: 2114471005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471006) == "Az Igni is szétszaggatja az embereket", "w3string.byId: 2114471006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471007) == "Szaggasd szét, amit az Igni megöl", "w3string.byId: 2114471007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471008) == "Lassítás esélye szétszaggatáskor", "w3string.byId: 2114471008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471009) == "   ...erősség (kisebb = erősebb)", "w3string.byId: 2114471009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471010) == "   ...időtartam, mp", "w3string.byId: 2114471010")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("ssht_menu") == "Jelrobbantás", "w3string.byKey: ssht_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_humanpoise") == "Megtört egyensúlyú emberek szétszaggatása", "w3string.byKey: ssht_humanpoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_humanhp") == "   ...csak ezen életerő % alatt", "w3string.byKey: ssht_humanhp")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_shatterscale") == "   ...esélygörbe (100 = egy az egyhez)", "w3string.byKey: ssht_shatterscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_killshatter") == "Szaggasd szét, amit az Aard megöl", "w3string.byKey: ssht_killshatter")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_killshatterhumans") == "   ...embereket is", "w3string.byKey: ssht_killshatterhumans")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_ignipoise") == "Az Igni is szétszaggatja az embereket", "w3string.byKey: ssht_ignipoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_ignikill") == "Szaggasd szét, amit az Igni megöl", "w3string.byKey: ssht_ignikill")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomochance") == "Lassítás esélye szétszaggatáskor", "w3string.byKey: ssht_slomochance")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomoscale") == "   ...erősség (kisebb = erősebb)", "w3string.byKey: ssht_slomoscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomotime") == "   ...időtartam, mp", "w3string.byKey: ssht_slomotime")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
