
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114471000) == "İşaretle Parçalama", "w3string.byId: 2114471000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471001) == "Dengesi bozulan insanları parçala", "w3string.byId: 2114471001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471002) == "   ...yalnızca bu can yüzdesinin altında", "w3string.byId: 2114471002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471003) == "   ...şans eğrisi (100 = bire bir)", "w3string.byId: 2114471003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471004) == "Aard'ın öldürdüğü her şeyi parçala", "w3string.byId: 2114471004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471005) == "   ...insanlar dahil", "w3string.byId: 2114471005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471006) == "Igni de insanları parçalar", "w3string.byId: 2114471006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471007) == "Igni'nin öldürdüğü her şeyi parçala", "w3string.byId: 2114471007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471008) == "Parçalamada ağır çekim şansı", "w3string.byId: 2114471008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471009) == "   ...güç (düşük = daha güçlü)", "w3string.byId: 2114471009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471010) == "   ...süre, sn", "w3string.byId: 2114471010")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("ssht_menu") == "İşaretle Parçalama", "w3string.byKey: ssht_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_humanpoise") == "Dengesi bozulan insanları parçala", "w3string.byKey: ssht_humanpoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_humanhp") == "   ...yalnızca bu can yüzdesinin altında", "w3string.byKey: ssht_humanhp")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_shatterscale") == "   ...şans eğrisi (100 = bire bir)", "w3string.byKey: ssht_shatterscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_killshatter") == "Aard'ın öldürdüğü her şeyi parçala", "w3string.byKey: ssht_killshatter")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_killshatterhumans") == "   ...insanlar dahil", "w3string.byKey: ssht_killshatterhumans")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_ignipoise") == "Igni de insanları parçalar", "w3string.byKey: ssht_ignipoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_ignikill") == "Igni'nin öldürdüğü her şeyi parçala", "w3string.byKey: ssht_ignikill")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomochance") == "Parçalamada ağır çekim şansı", "w3string.byKey: ssht_slomochance")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomoscale") == "   ...güç (düşük = daha güçlü)", "w3string.byKey: ssht_slomoscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomotime") == "   ...süre, sn", "w3string.byKey: ssht_slomotime")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
