
// autogenerated tests for w3strings (require modBase-Utils)
// language: en

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114471000) == "Sign Shatter", "w3string.byId: 2114471000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471001) == "Shatter humans with broken poise", "w3string.byId: 2114471001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471002) == "   ...only below this health %", "w3string.byId: 2114471002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471003) == "   ...chance curve (100 = one to one)", "w3string.byId: 2114471003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471004) == "Shatter anything Aard kills", "w3string.byId: 2114471004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471005) == "   ...including humans", "w3string.byId: 2114471005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471006) == "Igni shatters humans too", "w3string.byId: 2114471006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471007) == "Shatter anything Igni kills", "w3string.byId: 2114471007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471008) == "Slow motion chance on shatter", "w3string.byId: 2114471008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471009) == "   ...strength (lower = stronger)", "w3string.byId: 2114471009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471010) == "   ...duration, sec", "w3string.byId: 2114471010")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("ssht_menu") == "Sign Shatter", "w3string.byKey: ssht_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_humanpoise") == "Shatter humans with broken poise", "w3string.byKey: ssht_humanpoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_humanhp") == "   ...only below this health %", "w3string.byKey: ssht_humanhp")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_shatterscale") == "   ...chance curve (100 = one to one)", "w3string.byKey: ssht_shatterscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_killshatter") == "Shatter anything Aard kills", "w3string.byKey: ssht_killshatter")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_killshatterhumans") == "   ...including humans", "w3string.byKey: ssht_killshatterhumans")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_ignipoise") == "Igni shatters humans too", "w3string.byKey: ssht_ignipoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_ignikill") == "Shatter anything Igni kills", "w3string.byKey: ssht_ignikill")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomochance") == "Slow motion chance on shatter", "w3string.byKey: ssht_slomochance")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomoscale") == "   ...strength (lower = stronger)", "w3string.byKey: ssht_slomoscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomotime") == "   ...duration, sec", "w3string.byKey: ssht_slomotime")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
