
// autogenerated tests for w3strings (require modBase-Utils)
// language: ru

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114471000) == "Разрыв знаками", "w3string.byId: 2114471000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471001) == "Разрывать людей со сбитой стойкой", "w3string.byId: 2114471001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471002) == "   ...только ниже этого % здоровья", "w3string.byId: 2114471002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471003) == "   ...крутизна кривой шанса (100 = один к одному)", "w3string.byId: 2114471003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471004) == "Разрывать всех, кого добил Аард", "w3string.byId: 2114471004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471005) == "   ...включая людей", "w3string.byId: 2114471005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471006) == "Игни разрывает людей так же", "w3string.byId: 2114471006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471007) == "Разрывать всех, кого добил Игни", "w3string.byId: 2114471007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471008) == "Шанс замедления времени при разрыве", "w3string.byId: 2114471008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471009) == "   ...сила замедления (меньше = сильнее)", "w3string.byId: 2114471009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471010) == "   ...длительность, сек", "w3string.byId: 2114471010")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("ssht_menu") == "Разрыв знаками", "w3string.byKey: ssht_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_humanpoise") == "Разрывать людей со сбитой стойкой", "w3string.byKey: ssht_humanpoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_humanhp") == "   ...только ниже этого % здоровья", "w3string.byKey: ssht_humanhp")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_shatterscale") == "   ...крутизна кривой шанса (100 = один к одному)", "w3string.byKey: ssht_shatterscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_killshatter") == "Разрывать всех, кого добил Аард", "w3string.byKey: ssht_killshatter")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_killshatterhumans") == "   ...включая людей", "w3string.byKey: ssht_killshatterhumans")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_ignipoise") == "Игни разрывает людей так же", "w3string.byKey: ssht_ignipoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_ignikill") == "Разрывать всех, кого добил Игни", "w3string.byKey: ssht_ignikill")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomochance") == "Шанс замедления времени при разрыве", "w3string.byKey: ssht_slomochance")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomoscale") == "   ...сила замедления (меньше = сильнее)", "w3string.byKey: ssht_slomoscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomotime") == "   ...длительность, сек", "w3string.byKey: ssht_slomotime")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
