
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114478000) == "W3EE Redux Eklentileri", "w3string.byId: 2114478000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478001) == "Böceksi Mutasyon Düzeltmesi", "w3string.byId: 2114478001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478002) == "Toksisite dönüşüm oranını düzelt", "w3string.byId: 2114478002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478003) == "   ...puan başına saniyenin yüzde biri (orijinal 10)", "w3string.byId: 2114478003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478004) == "Gerçek oranı açıklamada göster", "w3string.byId: 2114478004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478005) == "Orijinal hasar azaltmayı geri getir", "w3string.byId: 2114478005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478006) == "   ...tekrar eden vuruşlarda azaltma, %", "w3string.byId: 2114478006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478007) == "   ...pencere süresi, sn", "w3string.byId: 2114478007")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux Eklentileri", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_menu") == "Böceksi Mutasyon Düzeltmesi", "w3string.byKey: insc_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_enabled") == "Toksisite dönüşüm oranını düzelt", "w3string.byKey: insc_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_rate") == "   ...puan başına saniyenin yüzde biri (orijinal 10)", "w3string.byKey: insc_rate")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_fixdesc") == "Gerçek oranı açıklamada göster", "w3string.byKey: insc_fixdesc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredon") == "Orijinal hasar azaltmayı geri getir", "w3string.byKey: insc_dmgredon")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredperc") == "   ...tekrar eden vuruşlarda azaltma, %", "w3string.byKey: insc_dmgredperc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredwin") == "   ...pencere süresi, sn", "w3string.byKey: insc_dmgredwin")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
