
// autogenerated tests for w3strings (require modBase-Utils)
// language: pl

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114479000) == "Dodatki do W3EE Redux", "w3string.byId: 2114479000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479001) == "Uczciwe Liczby", "w3string.byId: 2114479001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479002) == "Uczciwe liczby włączone", "w3string.byId: 2114479002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479003) == "Wiersze Znaków: pokaż realną moc każdego Znaku", "w3string.byId: 2114479003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479004) == "Obrażenia mieczy: uwzględnij zużycie ostrza, jak w walce", "w3string.byId: 2114479004")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Dodatki do W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_menu") == "Uczciwe Liczby", "w3string.byKey: hnum_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_enabled") == "Uczciwe liczby włączone", "w3string.byKey: hnum_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_signrows") == "Wiersze Znaków: pokaż realną moc każdego Znaku", "w3string.byKey: hnum_signrows")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_durability") == "Obrażenia mieczy: uwzględnij zużycie ostrza, jak w walce", "w3string.byKey: hnum_durability")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
