
// autogenerated tests for w3strings (require modBase-Utils)
// language: fr

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114472000) == "Modules W3EE Redux", "w3string.byId: 2114472000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472001) == "Démembrer Tout le Monde", "w3string.byId: 2114472001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472002) == "Démembrer les humains en armure", "w3string.byId: 2114472002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472003) == "   ...chance", "w3string.byId: 2114472003")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Modules W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_menu") == "Démembrer Tout le Monde", "w3string.byKey: dsma_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_armordism") == "Démembrer les humains en armure", "w3string.byKey: dsma_armordism")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_armorchance") == "   ...chance", "w3string.byKey: dsma_armorchance")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
