
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114477000) == "إضافات W3EE Redux", "w3string.byId: 2114477000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477001) == "مكافآت الأطقم حسب المستوى", "w3string.byId: 2114477001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477002) == "مكافأة الأستاذية في كل المستويات", "w3string.byId: 2114477002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477003) == "   ...القوة في المستوى 1، %", "w3string.byId: 2114477003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477004) == "   ...القوة في المستوى 2، %", "w3string.byId: 2114477004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477005) == "   ...القوة في المستوى 3، %", "w3string.byId: 2114477005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477006) == "   ...القوة في المستوى 4، %", "w3string.byId: 2114477006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477007) == "في الوصف: قيمة الأستاذية بين قوسين", "w3string.byId: 2114477007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477008) == "في الوصف: سطر عن قوة المكافأة", "w3string.byId: 2114477008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477009) == "القوة حسب المستوى:", "w3string.byId: 2114477009")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "إضافات W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_menu") == "مكافآت الأطقم حسب المستوى", "w3string.byKey: tssb_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_enabled") == "مكافأة الأستاذية في كل المستويات", "w3string.byKey: tssb_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier1") == "   ...القوة في المستوى 1، %", "w3string.byKey: tssb_tier1")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier2") == "   ...القوة في المستوى 2، %", "w3string.byKey: tssb_tier2")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier3") == "   ...القوة في المستوى 3، %", "w3string.byKey: tssb_tier3")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier4") == "   ...القوة في المستوى 4، %", "w3string.byKey: tssb_tier4")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_descgm") == "في الوصف: قيمة الأستاذية بين قوسين", "w3string.byKey: tssb_descgm")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_descnote") == "في الوصف: سطر عن قوة المكافأة", "w3string.byKey: tssb_descnote")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_note") == "القوة حسب المستوى:", "w3string.byKey: tssb_note")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
