
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114490000) == "W3EE Redux 애드온", "w3string.byId: 2114490000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490001) == "Dynamic Ragdolls", "w3string.byId: 2114490001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490002) == "Free ragdoll death chance (%)", "w3string.byId: 2114490002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490003) == "Ragdoll impulse strength (%)", "w3string.byId: 2114490003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490004) == "Mute corpses on sign hits", "w3string.byId: 2114490004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490005) == "Drop weapons on non-sword deaths", "w3string.byId: 2114490005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490006) == "Deadly Counter (Mutation 3, low health)", "w3string.byId: 2114490006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490007) == "Fists never dismember", "w3string.byId: 2114490007")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux 애드온", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_menu") == "Dynamic Ragdolls", "w3string.byKey: drgd_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_chance") == "Free ragdoll death chance (%)", "w3string.byKey: drgd_chance")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_force") == "Ragdoll impulse strength (%)", "w3string.byKey: drgd_force")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_mute") == "Mute corpses on sign hits", "w3string.byKey: drgd_mute")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_drop") == "Drop weapons on non-sword deaths", "w3string.byKey: drgd_drop")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_deadly") == "Deadly Counter (Mutation 3, low health)", "w3string.byKey: drgd_deadly")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_fists") == "Fists never dismember", "w3string.byKey: drgd_fists")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
