
// autogenerated tests for w3strings (require modBase-Utils)
// language: jp

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114478000) == "W3EE Redux アドオン", "w3string.byId: 2114478000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478001) == "インセクトイド変異の修正", "w3string.byId: 2114478001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478002) == "毒性の交換レートを修正", "w3string.byId: 2114478002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478003) == "   ...1ポイントあたり1/100秒 (原作は10)", "w3string.byId: 2114478003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478004) == "説明に実際のレートを表示", "w3string.byId: 2114478004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478005) == "バニラのダメージ軽減を復活", "w3string.byId: 2114478005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478006) == "   ...連続被弾時の軽減, %", "w3string.byId: 2114478006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478007) == "   ...持続ウィンドウ, 秒", "w3string.byId: 2114478007")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux アドオン", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_menu") == "インセクトイド変異の修正", "w3string.byKey: insc_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_enabled") == "毒性の交換レートを修正", "w3string.byKey: insc_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_rate") == "   ...1ポイントあたり1/100秒 (原作は10)", "w3string.byKey: insc_rate")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_fixdesc") == "説明に実際のレートを表示", "w3string.byKey: insc_fixdesc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredon") == "バニラのダメージ軽減を復活", "w3string.byKey: insc_dmgredon")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredperc") == "   ...連続被弾時の軽減, %", "w3string.byKey: insc_dmgredperc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredwin") == "   ...持続ウィンドウ, 秒", "w3string.byKey: insc_dmgredwin")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
