
// autogenerated tests for w3strings (require modBase-Utils)
// language: ru

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114490000) == "Надстройки W3EE Redux", "w3string.byId: 2114490000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490001) == "Рэгдоллы и смерти", "w3string.byId: 2114490001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490002) == "Шанс рэгдолл-смерти (%)", "w3string.byId: 2114490002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490003) == "Сила отброса тела (%)", "w3string.byId: 2114490003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490004) == "Тишина трупов при добивании знаками", "w3string.byId: 2114490004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490005) == "Ронять оружие (огонь, яд, бочки)", "w3string.byId: 2114490005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490006) == "Смертельный контрудар (Мутация 3)", "w3string.byId: 2114490006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114490007) == "Кулаки не расчленяют", "w3string.byId: 2114490007")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Надстройки W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_menu") == "Рэгдоллы и смерти", "w3string.byKey: drgd_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_chance") == "Шанс рэгдолл-смерти (%)", "w3string.byKey: drgd_chance")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_force") == "Сила отброса тела (%)", "w3string.byKey: drgd_force")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_mute") == "Тишина трупов при добивании знаками", "w3string.byKey: drgd_mute")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_drop") == "Ронять оружие (огонь, яд, бочки)", "w3string.byKey: drgd_drop")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_deadly") == "Смертельный контрудар (Мутация 3)", "w3string.byKey: drgd_deadly")) failed += 1;
    if (!assertTrue(GetLocStringByKey("drgd_fists") == "Кулаки не расчленяют", "w3string.byKey: drgd_fists")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
