
// autogenerated tests for w3strings (require modBase-Utils)
// language: hu

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114478000) == "W3EE Redux kiegészítők", "w3string.byId: 2114478000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478001) == "Mutáció-javítások", "w3string.byId: 2114478001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478002) == "Mutáció-javítások bekapcsolva", "w3string.byId: 2114478002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478003) == "Rovar: meregtelenites ures adrenalinnal, %", "w3string.byId: 2114478003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478004) == "Rovar: meregtelenites teli adrenalinnal, %", "w3string.byId: 2114478004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478005) == "Rovar: csak harcban mukodik", "w3string.byId: 2114478005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478006) == "Valós számok a mutációk leírásában", "w3string.byId: 2114478006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478007) == "Rovar: az eltávolított sebzéscsökkentés visszaállítása", "w3string.byId: 2114478007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478008) == "   ...mennyivel gyengébbek az ismételt találatok, %", "w3string.byId: 2114478008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478009) == "   ...hány másodpercig tart", "w3string.byId: 2114478009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478010) == "Kísértet: a jelbónusz emelése az ígért +50%-ra (0 = ahogy a játékban)", "w3string.byId: 2114478010")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478011) == "Karakterlap: a jelerő mutatása a csökkenés után", "w3string.byId: 2114478011")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux kiegészítők", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_menu") == "Mutáció-javítások", "w3string.byKey: mutf_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_enabled") == "Mutáció-javítások bekapcsolva", "w3string.byKey: mutf_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_adrfloor") == "Rovar: meregtelenites ures adrenalinnal, %", "w3string.byKey: mutf_adrfloor")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_adrtop") == "Rovar: meregtelenites teli adrenalinnal, %", "w3string.byKey: mutf_adrtop")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_combatonly") == "Rovar: csak harcban mukodik", "w3string.byKey: mutf_combatonly")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_fixdesc") == "Valós számok a mutációk leírásában", "w3string.byKey: mutf_fixdesc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredon") == "Rovar: az eltávolított sebzéscsökkentés visszaállítása", "w3string.byKey: insc_dmgredon")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredperc") == "   ...mennyivel gyengébbek az ismételt találatok, %", "w3string.byKey: insc_dmgredperc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredwin") == "   ...hány másodpercig tart", "w3string.byKey: insc_dmgredwin")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_signbypass") == "Kísértet: a jelbónusz emelése az ígért +50%-ra (0 = ahogy a játékban)", "w3string.byKey: mutf_signbypass")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_sheet") == "Karakterlap: a jelerő mutatása a csökkenés után", "w3string.byKey: mutf_sheet")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
