
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114477000) == "W3EE Redux Eklentileri", "w3string.byId: 2114477000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477001) == "Seviyeye Göre Set Bonusları", "w3string.byId: 2114477001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477002) == "Her seviyede büyük usta bonusu", "w3string.byId: 2114477002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477003) == "   ...1. seviyede güç, %", "w3string.byId: 2114477003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477004) == "   ...2. seviyede güç, %", "w3string.byId: 2114477004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477005) == "   ...3. seviyede güç, %", "w3string.byId: 2114477005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477006) == "   ...4. seviyede güç, %", "w3string.byId: 2114477006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477007) == "Açıklamada: büyük usta değeri parantezde", "w3string.byId: 2114477007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477008) == "Açıklamada: bonus gücü satırı", "w3string.byId: 2114477008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477009) == "Seviyeye göre güç:", "w3string.byId: 2114477009")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux Eklentileri", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_menu") == "Seviyeye Göre Set Bonusları", "w3string.byKey: tssb_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_enabled") == "Her seviyede büyük usta bonusu", "w3string.byKey: tssb_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier1") == "   ...1. seviyede güç, %", "w3string.byKey: tssb_tier1")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier2") == "   ...2. seviyede güç, %", "w3string.byKey: tssb_tier2")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier3") == "   ...3. seviyede güç, %", "w3string.byKey: tssb_tier3")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier4") == "   ...4. seviyede güç, %", "w3string.byKey: tssb_tier4")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_descgm") == "Açıklamada: büyük usta değeri parantezde", "w3string.byKey: tssb_descgm")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_descnote") == "Açıklamada: bonus gücü satırı", "w3string.byKey: tssb_descnote")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_note") == "Seviyeye göre güç:", "w3string.byKey: tssb_note")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
