
// autogenerated tests for w3strings (require modBase-Utils)
// language: es

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114472000) == "Complementos de W3EE Redux", "w3string.byId: 2114472000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472001) == "Desmembrar a Cualquiera", "w3string.byId: 2114472001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472002) == "Desmembrar humanos con armadura", "w3string.byId: 2114472002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472003) == "   ...probabilidad", "w3string.byId: 2114472003")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Complementos de W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_menu") == "Desmembrar a Cualquiera", "w3string.byKey: dsma_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_armordism") == "Desmembrar humanos con armadura", "w3string.byKey: dsma_armordism")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_armorchance") == "   ...probabilidad", "w3string.byKey: dsma_armorchance")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
