
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114473000) == "W3EE Redux Eklentileri", "w3string.byId: 2114473000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114473001) == "Bitiriş Çeşitliliği", "w3string.byId: 2114473001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114473002) == "Çeşitlilik: 0 W3EE, 1 orijinal, 2 maks", "w3string.byId: 2114473002")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux Eklentileri", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("fvar_menu") == "Bitiriş Çeşitliliği", "w3string.byKey: fvar_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("fvar_mode") == "Çeşitlilik: 0 W3EE, 1 orijinal, 2 maks", "w3string.byKey: fvar_mode")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
