
// autogenerated tests for w3strings (require modBase-Utils)
// language: hu

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114477000) == "W3EE Redux kiegészítők", "w3string.byId: 2114477000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477001) == "Szintarányos Szett Bónuszok", "w3string.byId: 2114477001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477002) == "Nagymesteri bónusz minden szinten", "w3string.byId: 2114477002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477003) == "   ...erő 1. szinten, %", "w3string.byId: 2114477003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477004) == "   ...erő 2. szinten, %", "w3string.byId: 2114477004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477005) == "   ...erő 3. szinten, %", "w3string.byId: 2114477005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477006) == "   ...erő 4. szinten, %", "w3string.byId: 2114477006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477007) == "Leírásban: nagymesteri érték zárójelben", "w3string.byId: 2114477007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477008) == "Leírásban: sor a bónusz erejéről", "w3string.byId: 2114477008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477009) == "Szint szerinti erő:", "w3string.byId: 2114477009")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux kiegészítők", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_menu") == "Szintarányos Szett Bónuszok", "w3string.byKey: tssb_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_enabled") == "Nagymesteri bónusz minden szinten", "w3string.byKey: tssb_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier1") == "   ...erő 1. szinten, %", "w3string.byKey: tssb_tier1")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier2") == "   ...erő 2. szinten, %", "w3string.byKey: tssb_tier2")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier3") == "   ...erő 3. szinten, %", "w3string.byKey: tssb_tier3")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier4") == "   ...erő 4. szinten, %", "w3string.byKey: tssb_tier4")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_descgm") == "Leírásban: nagymesteri érték zárójelben", "w3string.byKey: tssb_descgm")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_descnote") == "Leírásban: sor a bónusz erejéről", "w3string.byKey: tssb_descnote")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_note") == "Szint szerinti erő:", "w3string.byKey: tssb_note")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
