
// autogenerated tests for w3strings (require modBase-Utils)
// language: en

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114479000) == "W3EE Redux Add-ons", "w3string.byId: 2114479000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479001) == "Honest Numbers", "w3string.byId: 2114479001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479002) == "Honest numbers enabled", "w3string.byId: 2114479002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479003) == "Sign rows: show what each Sign really fires at", "w3string.byId: 2114479003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479004) == "Sword damage: count blade wear, as combat does", "w3string.byId: 2114479004")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux Add-ons", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_menu") == "Honest Numbers", "w3string.byKey: hnum_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_enabled") == "Honest numbers enabled", "w3string.byKey: hnum_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_signrows") == "Sign rows: show what each Sign really fires at", "w3string.byKey: hnum_signrows")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_durability") == "Sword damage: count blade wear, as combat does", "w3string.byKey: hnum_durability")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
