
// autogenerated tests for w3strings (require modBase-Utils)
// language: ru

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114474000) == "Надстройки W3EE Redux", "w3string.byId: 2114474000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114474001) == "Выбор мутаций Метаморфозы", "w3string.byId: 2114474001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114474002) == "Выбирать мутации в экране мутаций", "w3string.byId: 2114474002")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Надстройки W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mmpk_menu") == "Выбор мутаций Метаморфозы", "w3string.byKey: mmpk_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mmpk_enabled") == "Выбирать мутации в экране мутаций", "w3string.byKey: mmpk_enabled")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
