
// autogenerated tests for w3strings (require modBase-Utils)
// language: pl

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114477000) == "Dodatki do W3EE Redux", "w3string.byId: 2114477000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477001) == "Bonusy Zestawów wg Poziomu", "w3string.byId: 2114477001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477002) == "Bonus arcymistrzowski na każdym poziomie", "w3string.byId: 2114477002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477003) == "   ...siła na poziomie 1, %", "w3string.byId: 2114477003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477004) == "   ...siła na poziomie 2, %", "w3string.byId: 2114477004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477005) == "   ...siła na poziomie 3, %", "w3string.byId: 2114477005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477006) == "   ...siła na poziomie 4, %", "w3string.byId: 2114477006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477007) == "W opisie: wartość arcymistrzowska w nawiasie", "w3string.byId: 2114477007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477008) == "W opisie: wiersz o sile bonusu", "w3string.byId: 2114477008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477009) == "Siła wg poziomu:", "w3string.byId: 2114477009")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Dodatki do W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_menu") == "Bonusy Zestawów wg Poziomu", "w3string.byKey: tssb_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_enabled") == "Bonus arcymistrzowski na każdym poziomie", "w3string.byKey: tssb_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier1") == "   ...siła na poziomie 1, %", "w3string.byKey: tssb_tier1")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier2") == "   ...siła na poziomie 2, %", "w3string.byKey: tssb_tier2")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier3") == "   ...siła na poziomie 3, %", "w3string.byKey: tssb_tier3")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier4") == "   ...siła na poziomie 4, %", "w3string.byKey: tssb_tier4")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_descgm") == "W opisie: wartość arcymistrzowska w nawiasie", "w3string.byKey: tssb_descgm")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_descnote") == "W opisie: wiersz o sile bonusu", "w3string.byKey: tssb_descnote")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_note") == "Siła wg poziomu:", "w3string.byKey: tssb_note")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
