
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114478000) == "إضافات W3EE Redux", "w3string.byId: 2114478000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478001) == "إصلاح طفرة الحشرات", "w3string.byId: 2114478001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478002) == "إصلاح معدل تحويل السمية", "w3string.byId: 2114478002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478003) == "   ...من مئات الثانية لكل نقطة (الأصل 10)", "w3string.byId: 2114478003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478004) == "إظهار المعدل الحقيقي في الوصف", "w3string.byId: 2114478004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478005) == "إعادة تقليل الضرر الأصلي", "w3string.byId: 2114478005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478006) == "   ...التقليل عند الضربات المتكررة، %", "w3string.byId: 2114478006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478007) == "   ...طول النافذة بالثواني", "w3string.byId: 2114478007")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "إضافات W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_menu") == "إصلاح طفرة الحشرات", "w3string.byKey: insc_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_enabled") == "إصلاح معدل تحويل السمية", "w3string.byKey: insc_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_rate") == "   ...من مئات الثانية لكل نقطة (الأصل 10)", "w3string.byKey: insc_rate")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_fixdesc") == "إظهار المعدل الحقيقي في الوصف", "w3string.byKey: insc_fixdesc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredon") == "إعادة تقليل الضرر الأصلي", "w3string.byKey: insc_dmgredon")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredperc") == "   ...التقليل عند الضربات المتكررة، %", "w3string.byKey: insc_dmgredperc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredwin") == "   ...طول النافذة بالثواني", "w3string.byKey: insc_dmgredwin")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
