
// autogenerated tests for w3strings (require modBase-Utils)
// language: it

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114478000) == "Componenti aggiuntivi W3EE Redux", "w3string.byId: 2114478000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478001) == "Correzione Mutazione Insettoide", "w3string.byId: 2114478001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478002) == "Correggi il tasso di conversione della tossicità", "w3string.byId: 2114478002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478003) == "   ...centesimi di secondo per punto (originale 10)", "w3string.byId: 2114478003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478004) == "Mostra il tasso reale nella descrizione", "w3string.byId: 2114478004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478005) == "Ripristina la riduzione danni originale", "w3string.byId: 2114478005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478006) == "   ...riduzione sui colpi ripetuti, %", "w3string.byId: 2114478006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478007) == "   ...durata della finestra, sec", "w3string.byId: 2114478007")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Componenti aggiuntivi W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_menu") == "Correzione Mutazione Insettoide", "w3string.byKey: insc_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_enabled") == "Correggi il tasso di conversione della tossicità", "w3string.byKey: insc_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_rate") == "   ...centesimi di secondo per punto (originale 10)", "w3string.byKey: insc_rate")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_fixdesc") == "Mostra il tasso reale nella descrizione", "w3string.byKey: insc_fixdesc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredon") == "Ripristina la riduzione danni originale", "w3string.byKey: insc_dmgredon")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredperc") == "   ...riduzione sui colpi ripetuti, %", "w3string.byKey: insc_dmgredperc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredwin") == "   ...durata della finestra, sec", "w3string.byKey: insc_dmgredwin")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
