
// autogenerated tests for w3strings (require modBase-Utils)
// language: zh

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114478000) == "W3EE Redux 扩展", "w3string.byId: 2114478000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478001) == "突变修正", "w3string.byId: 2114478001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478002) == "启用突变修正", "w3string.byId: 2114478002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478003) == "虫类: 肾上腺素为空时的排毒速度 (%)", "w3string.byId: 2114478003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478004) == "虫类: 肾上腺素满时的排毒速度 (%)", "w3string.byId: 2114478004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478005) == "虫类: 仅在战斗中生效", "w3string.byId: 2114478005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478006) == "在突变描述中显示真实数值", "w3string.byId: 2114478006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478007) == "虫类: 恢复被移除的伤害减免", "w3string.byId: 2114478007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478008) == "   ...连续受击减弱多少, %", "w3string.byId: 2114478008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478009) == "   ...持续多少秒", "w3string.byId: 2114478009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478010) == "幽灵: 将法印加成提升至承诺的 +50% (0 = 保持原样)", "w3string.byId: 2114478010")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478011) == "角色面板: 显示衰减后的法印强度", "w3string.byId: 2114478011")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux 扩展", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_menu") == "突变修正", "w3string.byKey: mutf_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_enabled") == "启用突变修正", "w3string.byKey: mutf_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_adrfloor") == "虫类: 肾上腺素为空时的排毒速度 (%)", "w3string.byKey: mutf_adrfloor")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_adrtop") == "虫类: 肾上腺素满时的排毒速度 (%)", "w3string.byKey: mutf_adrtop")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_combatonly") == "虫类: 仅在战斗中生效", "w3string.byKey: mutf_combatonly")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_fixdesc") == "在突变描述中显示真实数值", "w3string.byKey: mutf_fixdesc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredon") == "虫类: 恢复被移除的伤害减免", "w3string.byKey: insc_dmgredon")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredperc") == "   ...连续受击减弱多少, %", "w3string.byKey: insc_dmgredperc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredwin") == "   ...持续多少秒", "w3string.byKey: insc_dmgredwin")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_signbypass") == "幽灵: 将法印加成提升至承诺的 +50% (0 = 保持原样)", "w3string.byKey: mutf_signbypass")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_sheet") == "角色面板: 显示衰减后的法印强度", "w3string.byKey: mutf_sheet")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
