
// autogenerated tests for w3strings (require modBase-Utils)
// language: zh

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114475000) == "W3EE Redux 擴充", "w3string.byId: 2114475000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114475001) == "關閉心跳聲", "w3string.byId: 2114475001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114475002) == "關閉低耐力時的心跳聲", "w3string.byId: 2114475002")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux 擴充", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("nhbt_menu") == "關閉心跳聲", "w3string.byKey: nhbt_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("nhbt_mute") == "關閉低耐力時的心跳聲", "w3string.byKey: nhbt_mute")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
