
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114478000) == "Complementos de W3EE Redux", "w3string.byId: 2114478000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478001) == "Arreglo de la Mutación Insectoide", "w3string.byId: 2114478001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478002) == "Corregir la tasa de conversión de toxicidad", "w3string.byId: 2114478002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478003) == "   ...centésimas de segundo por punto (original 10)", "w3string.byId: 2114478003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478004) == "Mostrar la tasa real en la descripción", "w3string.byId: 2114478004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478005) == "Restaurar la reducción de daño original", "w3string.byId: 2114478005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478006) == "   ...reducción en golpes repetidos, %", "w3string.byId: 2114478006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478007) == "   ...duración de la ventana, seg", "w3string.byId: 2114478007")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Complementos de W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_menu") == "Arreglo de la Mutación Insectoide", "w3string.byKey: insc_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_enabled") == "Corregir la tasa de conversión de toxicidad", "w3string.byKey: insc_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_rate") == "   ...centésimas de segundo por punto (original 10)", "w3string.byKey: insc_rate")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_fixdesc") == "Mostrar la tasa real en la descripción", "w3string.byKey: insc_fixdesc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredon") == "Restaurar la reducción de daño original", "w3string.byKey: insc_dmgredon")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredperc") == "   ...reducción en golpes repetidos, %", "w3string.byKey: insc_dmgredperc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredwin") == "   ...duración de la ventana, seg", "w3string.byKey: insc_dmgredwin")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
