
// autogenerated tests for w3strings (require modBase-Utils)
// language: zh

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114479000) == "W3EE Redux 扩展", "w3string.byId: 2114479000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479001) == "诚实的数值", "w3string.byId: 2114479001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479002) == "启用诚实数值", "w3string.byId: 2114479002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479003) == "法印各行: 显示每个法印的真实威力", "w3string.byId: 2114479003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479004) == "剑伤害: 像战斗中一样计入刀刃磨损", "w3string.byId: 2114479004")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux 扩展", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_menu") == "诚实的数值", "w3string.byKey: hnum_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_enabled") == "启用诚实数值", "w3string.byKey: hnum_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_signrows") == "法印各行: 显示每个法印的真实威力", "w3string.byKey: hnum_signrows")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_durability") == "剑伤害: 像战斗中一样计入刀刃磨损", "w3string.byKey: hnum_durability")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
