
// autogenerated tests for w3strings (require modBase-Utils)
// language: fr

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114479000) == "Modules W3EE Redux", "w3string.byId: 2114479000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479001) == "Chiffres Honnêtes", "w3string.byId: 2114479001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479002) == "Chiffres honnêtes activés", "w3string.byId: 2114479002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479003) == "Lignes de Signes : afficher la puissance réelle de chaque Signe", "w3string.byId: 2114479003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479004) == "Dégâts des épées : compter l'usure de la lame, comme en combat", "w3string.byId: 2114479004")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Modules W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_menu") == "Chiffres Honnêtes", "w3string.byKey: hnum_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_enabled") == "Chiffres honnêtes activés", "w3string.byKey: hnum_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_signrows") == "Lignes de Signes : afficher la puissance réelle de chaque Signe", "w3string.byKey: hnum_signrows")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_durability") == "Dégâts des épées : compter l'usure de la lame, comme en combat", "w3string.byKey: hnum_durability")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
