
// autogenerated tests for w3strings (require modBase-Utils)
// language: zh

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114474000) == "W3EE Redux 擴充", "w3string.byId: 2114474000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114474001) == "蛻變突變選擇器", "w3string.byId: 2114474001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114474002) == "在突變介面中選擇突變", "w3string.byId: 2114474002")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux 擴充", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mmpk_menu") == "蛻變突變選擇器", "w3string.byKey: mmpk_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mmpk_enabled") == "在突變介面中選擇突變", "w3string.byKey: mmpk_enabled")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
