
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114472000) == "W3EE Redux Eklentileri", "w3string.byId: 2114472000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472001) == "Herkesi Parçala", "w3string.byId: 2114472001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472002) == "Zırhlı insanları parçala", "w3string.byId: 2114472002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114472003) == "   ...şans", "w3string.byId: 2114472003")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux Eklentileri", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_menu") == "Herkesi Parçala", "w3string.byKey: dsma_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_armordism") == "Zırhlı insanları parçala", "w3string.byKey: dsma_armordism")) failed += 1;
    if (!assertTrue(GetLocStringByKey("dsma_armorchance") == "   ...şans", "w3string.byKey: dsma_armorchance")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
