
// autogenerated tests for w3strings (require modBase-Utils)
// language: en

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114478000) == "W3EE Redux Add-ons", "w3string.byId: 2114478000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478001) == "Mutation Fixes", "w3string.byId: 2114478001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478002) == "Mutation fixes enabled", "w3string.byId: 2114478002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478003) == "Insectoid: purge speed on an empty Adrenaline bar, %", "w3string.byId: 2114478003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478004) == "Insectoid: purge speed on a full Adrenaline bar, %", "w3string.byId: 2114478004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478005) == "Insectoid: only works in combat", "w3string.byId: 2114478005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478006) == "Show real numbers in mutation descriptions", "w3string.byId: 2114478006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478007) == "Insectoid: restore the removed damage reduction", "w3string.byId: 2114478007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478008) == "   ...how much weaker repeat hits are, %", "w3string.byId: 2114478008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478009) == "   ...how many seconds it lasts", "w3string.byId: 2114478009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478010) == "Specter: raise the Sign bonus toward the promised +50% (0 = as in game)", "w3string.byId: 2114478010")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478011) == "Character sheet: show Sign Intensity after falloff", "w3string.byId: 2114478011")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux Add-ons", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_menu") == "Mutation Fixes", "w3string.byKey: mutf_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_enabled") == "Mutation fixes enabled", "w3string.byKey: mutf_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_adrfloor") == "Insectoid: purge speed on an empty Adrenaline bar, %", "w3string.byKey: mutf_adrfloor")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_adrtop") == "Insectoid: purge speed on a full Adrenaline bar, %", "w3string.byKey: mutf_adrtop")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_combatonly") == "Insectoid: only works in combat", "w3string.byKey: mutf_combatonly")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_fixdesc") == "Show real numbers in mutation descriptions", "w3string.byKey: mutf_fixdesc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredon") == "Insectoid: restore the removed damage reduction", "w3string.byKey: insc_dmgredon")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredperc") == "   ...how much weaker repeat hits are, %", "w3string.byKey: insc_dmgredperc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredwin") == "   ...how many seconds it lasts", "w3string.byKey: insc_dmgredwin")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_signbypass") == "Specter: raise the Sign bonus toward the promised +50% (0 = as in game)", "w3string.byKey: mutf_signbypass")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_sheet") == "Character sheet: show Sign Intensity after falloff", "w3string.byKey: mutf_sheet")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
