
// autogenerated tests for w3strings (require modBase-Utils)
// language: cleartext

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114477000) == "Complementos do W3EE Redux", "w3string.byId: 2114477000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477001) == "Bônus de Conjunto por Nível", "w3string.byId: 2114477001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477002) == "Bônus de grão-mestre em todo nível", "w3string.byId: 2114477002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477003) == "   ...força no nível 1, %", "w3string.byId: 2114477003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477004) == "   ...força no nível 2, %", "w3string.byId: 2114477004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477005) == "   ...força no nível 3, %", "w3string.byId: 2114477005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477006) == "   ...força no nível 4, %", "w3string.byId: 2114477006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477007) == "Descrições: valor de grão-mestre entre parênteses", "w3string.byId: 2114477007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477008) == "Descrições: linha sobre a força do bônus", "w3string.byId: 2114477008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114477009) == "Força conforme o nível:", "w3string.byId: 2114477009")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Complementos do W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_menu") == "Bônus de Conjunto por Nível", "w3string.byKey: tssb_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_enabled") == "Bônus de grão-mestre em todo nível", "w3string.byKey: tssb_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier1") == "   ...força no nível 1, %", "w3string.byKey: tssb_tier1")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier2") == "   ...força no nível 2, %", "w3string.byKey: tssb_tier2")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier3") == "   ...força no nível 3, %", "w3string.byKey: tssb_tier3")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_tier4") == "   ...força no nível 4, %", "w3string.byKey: tssb_tier4")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_descgm") == "Descrições: valor de grão-mestre entre parênteses", "w3string.byKey: tssb_descgm")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_descnote") == "Descrições: linha sobre a força do bônus", "w3string.byKey: tssb_descnote")) failed += 1;
    if (!assertTrue(GetLocStringByKey("tssb_note") == "Força conforme o nível:", "w3string.byKey: tssb_note")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
