
// autogenerated tests for w3strings (require modBase-Utils)
// language: pl

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114471000) == "Dodatki do W3EE Redux", "w3string.byId: 2114471000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471001) == "Rozerwanie Znakiem", "w3string.byId: 2114471001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471002) == "Rozrywaj ludzi ze złamaną postawą", "w3string.byId: 2114471002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471003) == "   ...tylko poniżej tego % zdrowia", "w3string.byId: 2114471003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471004) == "   ...jak szybko szansa rośnie z ranami (100 = normalnie)", "w3string.byId: 2114471004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471005) == "Rozrywaj wszystko, co zabije Aard", "w3string.byId: 2114471005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471006) == "   ...w tym ludzi", "w3string.byId: 2114471006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471007) == "Igni też rozrywa ludzi", "w3string.byId: 2114471007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471008) == "Rozrywaj wszystko, co zabije Igni", "w3string.byId: 2114471008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471009) == "Rozrywaj wszystko, co zabije ogień", "w3string.byId: 2114471009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471010) == "Szansa na spowolnienie czasu", "w3string.byId: 2114471010")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471011) == "   ...siła (mniej = mocniej)", "w3string.byId: 2114471011")) failed += 1;
    if (!assertTrue(GetLocStringById(2114471012) == "   ...czas trwania, sek", "w3string.byId: 2114471012")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Dodatki do W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_menu") == "Rozerwanie Znakiem", "w3string.byKey: ssht_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_humanpoise") == "Rozrywaj ludzi ze złamaną postawą", "w3string.byKey: ssht_humanpoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_humanhp") == "   ...tylko poniżej tego % zdrowia", "w3string.byKey: ssht_humanhp")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_shatterscale") == "   ...jak szybko szansa rośnie z ranami (100 = normalnie)", "w3string.byKey: ssht_shatterscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_killshatter") == "Rozrywaj wszystko, co zabije Aard", "w3string.byKey: ssht_killshatter")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_killshatterhumans") == "   ...w tym ludzi", "w3string.byKey: ssht_killshatterhumans")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_ignipoise") == "Igni też rozrywa ludzi", "w3string.byKey: ssht_ignipoise")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_ignikill") == "Rozrywaj wszystko, co zabije Igni", "w3string.byKey: ssht_ignikill")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_burnkill") == "Rozrywaj wszystko, co zabije ogień", "w3string.byKey: ssht_burnkill")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomochance") == "Szansa na spowolnienie czasu", "w3string.byKey: ssht_slomochance")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomoscale") == "   ...siła (mniej = mocniej)", "w3string.byKey: ssht_slomoscale")) failed += 1;
    if (!assertTrue(GetLocStringByKey("ssht_slomotime") == "   ...czas trwania, sek", "w3string.byKey: ssht_slomotime")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
