
// autogenerated tests for w3strings (require modBase-Utils)
// language: it

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114479000) == "Componenti aggiuntivi W3EE Redux", "w3string.byId: 2114479000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479001) == "Numeri Onesti", "w3string.byId: 2114479001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479002) == "Numeri onesti attivi", "w3string.byId: 2114479002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479003) == "Righe dei Segni: mostra la potenza reale di ogni Segno", "w3string.byId: 2114479003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114479004) == "Danno delle spade: conta l'usura della lama, come in combattimento", "w3string.byId: 2114479004")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Componenti aggiuntivi W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_menu") == "Numeri Onesti", "w3string.byKey: hnum_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_enabled") == "Numeri onesti attivi", "w3string.byKey: hnum_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_signrows") == "Righe dei Segni: mostra la potenza reale di ogni Segno", "w3string.byKey: hnum_signrows")) failed += 1;
    if (!assertTrue(GetLocStringByKey("hnum_durability") == "Danno delle spade: conta l'usura della lama, come in combattimento", "w3string.byKey: hnum_durability")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
