
// autogenerated tests for w3strings (require modBase-Utils)
// language: ru

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114478000) == "Надстройки W3EE Redux", "w3string.byId: 2114478000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478001) == "Починка мутаций", "w3string.byId: 2114478001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478002) == "Починка мутаций включена", "w3string.byId: 2114478002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478003) == "Инсектоид: скорость выведения при пустом адреналине, %", "w3string.byId: 2114478003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478004) == "Инсектоид: скорость выведения при полном адреналине, %", "w3string.byId: 2114478004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478005) == "Инсектоид: работает только в бою", "w3string.byId: 2114478005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478006) == "Показывать в описаниях мутаций настоящие числа", "w3string.byId: 2114478006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478007) == "Инсектоид: вернуть вырезанное снижение урона", "w3string.byId: 2114478007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478008) == "   ...насколько слабее бьют повторные удары, %", "w3string.byId: 2114478008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478009) == "   ...сколько секунд это держится", "w3string.byId: 2114478009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478010) == "Призрак: доводить бонус знаков до обещанных +50% (0 — как в игре)", "w3string.byId: 2114478010")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478011) == "Окно персонажа: показывать мощь знаков с учётом затухания", "w3string.byId: 2114478011")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "Надстройки W3EE Redux", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_menu") == "Починка мутаций", "w3string.byKey: mutf_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_enabled") == "Починка мутаций включена", "w3string.byKey: mutf_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_adrfloor") == "Инсектоид: скорость выведения при пустом адреналине, %", "w3string.byKey: mutf_adrfloor")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_adrtop") == "Инсектоид: скорость выведения при полном адреналине, %", "w3string.byKey: mutf_adrtop")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_combatonly") == "Инсектоид: работает только в бою", "w3string.byKey: mutf_combatonly")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_fixdesc") == "Показывать в описаниях мутаций настоящие числа", "w3string.byKey: mutf_fixdesc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredon") == "Инсектоид: вернуть вырезанное снижение урона", "w3string.byKey: insc_dmgredon")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredperc") == "   ...насколько слабее бьют повторные удары, %", "w3string.byKey: insc_dmgredperc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredwin") == "   ...сколько секунд это держится", "w3string.byKey: insc_dmgredwin")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_signbypass") == "Призрак: доводить бонус знаков до обещанных +50% (0 — как в игре)", "w3string.byKey: mutf_signbypass")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_sheet") == "Окно персонажа: показывать мощь знаков с учётом затухания", "w3string.byKey: mutf_sheet")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
