
// autogenerated tests for w3strings (require modBase-Utils)
// language: zh

function _test_verifyW3strings() : int {
    var failed: int;
    failed = 0;

    // test by id
    if (!assertTrue(GetLocStringById(2114478000) == "W3EE Redux 擴充", "w3string.byId: 2114478000")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478001) == "突變修正", "w3string.byId: 2114478001")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478002) == "啟用突變修正", "w3string.byId: 2114478002")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478003) == "蟲類: 腎上腺素為空時的排毒速度 (%)", "w3string.byId: 2114478003")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478004) == "蟲類: 腎上腺素滿時的排毒速度 (%)", "w3string.byId: 2114478004")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478005) == "蟲類: 僅在戰鬥中生效", "w3string.byId: 2114478005")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478006) == "在突變描述中顯示真實數值", "w3string.byId: 2114478006")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478007) == "蟲類: 恢復被移除的傷害減免", "w3string.byId: 2114478007")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478008) == "   ...連續受擊減弱多少, %", "w3string.byId: 2114478008")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478009) == "   ...持續多少秒", "w3string.byId: 2114478009")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478010) == "幽靈: 將法印加成提升至承諾的 +50% (0 = 保持原樣)", "w3string.byId: 2114478010")) failed += 1;
    if (!assertTrue(GetLocStringById(2114478011) == "角色面板: 顯示衰減後的法印強度", "w3string.byId: 2114478011")) failed += 1;

    // test by key
    if (!assertTrue(GetLocStringByKey("w3eeredux_root") == "W3EE Redux 擴充", "w3string.byKey: w3eeredux_root")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_menu") == "突變修正", "w3string.byKey: mutf_menu")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_enabled") == "啟用突變修正", "w3string.byKey: mutf_enabled")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_adrfloor") == "蟲類: 腎上腺素為空時的排毒速度 (%)", "w3string.byKey: mutf_adrfloor")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_adrtop") == "蟲類: 腎上腺素滿時的排毒速度 (%)", "w3string.byKey: mutf_adrtop")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_combatonly") == "蟲類: 僅在戰鬥中生效", "w3string.byKey: mutf_combatonly")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_fixdesc") == "在突變描述中顯示真實數值", "w3string.byKey: mutf_fixdesc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredon") == "蟲類: 恢復被移除的傷害減免", "w3string.byKey: insc_dmgredon")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredperc") == "   ...連續受擊減弱多少, %", "w3string.byKey: insc_dmgredperc")) failed += 1;
    if (!assertTrue(GetLocStringByKey("insc_dmgredwin") == "   ...持續多少秒", "w3string.byKey: insc_dmgredwin")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_signbypass") == "幽靈: 將法印加成提升至承諾的 +50% (0 = 保持原樣)", "w3string.byKey: mutf_signbypass")) failed += 1;
    if (!assertTrue(GetLocStringByKey("mutf_sheet") == "角色面板: 顯示衰減後的法印強度", "w3string.byKey: mutf_sheet")) failed += 1;

    // return number of failed
    return failed;
}

exec function test_verifyW3Strings() {
    logTestResult("Verify W3Strings", _test_verifyW3strings(), true);
}
