# -*- coding: utf-8 -*-
"""
Описание пяти модов-надстроек над W3EE Redux и переводы их подписей.

Один мод = одна папка + один файл .ws + (если есть настройки) своё меню,
своя группа настроек и свой id-space строк. Общего ядра нет: помощники
продублированы в каждом моде под своим префиксом, поэтому любой мод можно
поставить, снять или обновить, не трогая остальные.
"""

GAME = r"F:\SteamLibrary\steamapps\common\The Witcher 3"

# все локали, которые понимает игра (content0)
LOCALES = ["ar", "br", "cn", "cz", "de", "en", "es", "esmx",
           "fr", "hu", "it", "jp", "kr", "pl", "ru", "tr", "zh"]

# Путь в дереве меню: «Дополнения» внутри блока W3EE, и ещё один уровень —
# общая папка для всех наших модов.
#
# ⚠️ Меню игры рисует ТОЛЬКО 10 пунктов на страницу (9 + «Назад»), остальные
# молча пропадают — это ограничение движка, а не наша ошибка. Займи мы по строке
# на мод, шесть модов вытеснили бы чужие. Поэтому все прячутся под один пункт.
MENU_ROOT = "w3eeredux_root"
MENU_PATH = "Mods.W3EE_w3ee.W3EE_addons." + MENU_ROOT + "."


# ---------------------------------------------------------------------------
#  Моды
#     vars: (varId, ключ подписи, displayType, значение по умолчанию)
# ---------------------------------------------------------------------------

MODS = [
    dict(
        mod="modW3EERedux_SignShatter", group="W3EERedux_SignShatter",
        oldmod="modSignShatter", oldgroup="SignShatter", src="SignShatter.ws",
        idspace=4471, priority=15, menu_key="ssht_menu",
        title="W3EE Redux - Sign Shatter",
        vars=[
            ("HumanPoise",        "ssht_humanpoise",        "TOGGLE",              "true"),
            ("HumanHP",           "ssht_humanhp",           "SLIDER;0;100;100",    "100"),
            ("ShatterScale",      "ssht_shatterscale",      "SLIDER;0;200;200",    "100"),
            ("KillShatter",       "ssht_killshatter",       "TOGGLE",              "true"),
            ("KillShatterHumans", "ssht_killshatterhumans", "TOGGLE",              "true"),
            ("IgniPoise",         "ssht_ignipoise",         "TOGGLE",              "true"),
            ("IgniKill",          "ssht_ignikill",          "TOGGLE",              "true"),
            ("BurnKill",          "ssht_burnkill",          "TOGGLE",              "true"),
            ("SloMoChance",       "ssht_slomochance",       "SLIDER;0;100;100",    "35"),
            ("SloMoScale",        "ssht_slomoscale",        "SLIDER;0.10;1.00;90", "0.30"),
            ("SloMoTime",         "ssht_slomotime",         "SLIDER;0.1;1.5;140",  "0.50"),
        ],
    ),
    dict(
        mod="modW3EERedux_DismemberAnyone", group="W3EERedux_DismemberAnyone",
        oldmod="modDismemberAnyone", oldgroup="DismemberAnyone", src="DismemberAnyone.ws",
        idspace=4472, priority=15, menu_key="dsma_menu",
        title="W3EE Redux - Dismember Anyone",
        vars=[
            ("ArmorDism",   "dsma_armordism",   "TOGGLE",           "true"),
            ("ArmorChance", "dsma_armorchance", "SLIDER;0;100;100", "100"),
        ],
    ),
    dict(
        mod="modW3EERedux_FinisherVariety", group="W3EERedux_FinisherVariety",
        oldmod="modFinisherVariety", oldgroup="FinisherVariety", src="FinisherVariety.ws",
        idspace=4473, priority=15, menu_key="fvar_menu",
        title="W3EE Redux - Finisher Variety",
        vars=[
            ("Mode", "fvar_mode", "SLIDER;0;2;2", "1"),
        ],
    ),
    dict(
        mod="modW3EERedux_MetamorphPicker", group="W3EERedux_MetamorphPicker",
        oldmod="modMetamorphPicker", oldgroup="MetamorphPicker", src="MetamorphPicker.ws",
        idspace=4474, priority=15, menu_key="mmpk_menu",
        title="W3EE Redux - Metamorphosis Picker",
        vars=[
            ("Enabled", "mmpk_enabled", "TOGGLE", "true"),
        ],
    ),
    dict(
        mod="modW3EERedux_NoHeartbeat", group="W3EERedux_NoHeartbeat",
        oldmod=None, oldgroup=None, src="NoHeartbeat.ws",
        idspace=4475, priority=15, menu_key="nhbt_menu",
        title="W3EE Redux - No Heartbeat",
        vars=[
            ("Mute", "nhbt_mute", "TOGGLE", "true"),
        ],
    ),
    dict(
        mod="modW3EERedux_TierBonuses", group="W3EERedux_TierBonuses",
        oldmod=None, oldgroup=None, src="TierBonuses.ws",
        idspace=4477, priority=15, menu_key="tssb_menu",
        title="W3EE Redux - Tier-Scaled Set Bonuses",
        # tssb_note подставляется не в меню, а прямо в описание бонуса в игре
        extra_keys=["tssb_note"],
        vars=[
            ("Enabled",  "tssb_enabled",  "TOGGLE",           "true"),
            ("Tier1",    "tssb_tier1",    "SLIDER;0;100;100", "40"),
            ("Tier2",    "tssb_tier2",    "SLIDER;0;100;100", "55"),
            ("Tier3",    "tssb_tier3",    "SLIDER;0;100;100", "70"),
            ("Tier4",    "tssb_tier4",    "SLIDER;0;100;100", "85"),
            ("DescGM",   "tssb_descgm",   "TOGGLE",           "true"),
            ("DescNote", "tssb_descnote", "TOGGLE",           "true"),
        ],
    ),
    dict(
        mod="modW3EERedux_Mutations", group="W3EERedux_Mutations",
        oldmod="modW3EERedux_Insectoid", oldgroup="W3EERedux_Insectoid", src="Mutations.ws",
        idspace=4478, priority=15, menu_key="mutf_menu",
        title="W3EE Redux - Mutation Fixes",
        vars=[
            ("Enabled",      "mutf_enabled",   "TOGGLE",           "true"),
            ("AdrFloor",     "mutf_adrfloor",  "SLIDER;0;200;200", "50"),
            ("AdrTop",       "mutf_adrtop",    "SLIDER;0;500;500", "300"),
            ("CombatOnly",   "mutf_combatonly","TOGGLE",           "true"),
            ("FixDesc",      "mutf_fixdesc",   "TOGGLE",           "true"),
            ("DmgRedOn",     "insc_dmgredon",  "TOGGLE",           "false"),
            ("DmgRedPerc",   "insc_dmgredperc","SLIDER;0;50;50",   "15"),
            ("DmgRedWindow", "insc_dmgredwin", "SLIDER;1;15;14",   "5"),
            ("SignBypass",   "mutf_signbypass","SLIDER;0;100;100", "0"),
            ("SheetHonest",  "mutf_sheet",     "TOGGLE",           "true"),
        ],
    ),
    dict(
        mod="modW3EERedux_HonestNumbers", group="W3EERedux_HonestNumbers",
        oldmod=None, oldgroup=None, src="HonestNumbers.ws",
        idspace=4479, priority=15, menu_key="hnum_menu",
        title="W3EE Redux - Honest Numbers",
        vars=[
            ("Enabled",    "hnum_enabled",    "TOGGLE", "true"),
            ("SignRows",   "hnum_signrows",   "TOGGLE", "true"),
            ("Durability", "hnum_durability", "TOGGLE", "true"),
        ],
    ),
    # Настройки для ручного мержа Dynamic Ragdolls (kingslayer997):
    # сами игровые блоки живут в mod0000_MergedFiles/damageManagerProcessor
    # (merge_ragdolls_final.py), тут только меню и функции-читалки.
    dict(
        mod="modW3EERedux_DynRagdolls", group="W3EERedux_DynRagdolls",
        oldmod=None, oldgroup=None, src="DynRagdolls.ws",
        idspace=4490, priority=15, menu_key="drgd_menu",
        title="W3EE Redux - Dynamic Ragdolls Settings",
        vars=[
            ("RagdollChance",    "drgd_chance", "SLIDER;0;100;100",  "10"),
            ("ForceScale",       "drgd_force",  "SLIDER;50;300;250", "100"),
            ("MuteCorpses",      "drgd_mute",   "TOGGLE",            "true"),
            ("DropWeapons",      "drgd_drop",   "TOGGLE",            "true"),
            ("DeadlyCounter",    "drgd_deadly", "TOGGLE",            "true"),
            ("FistsNoDismember", "drgd_fists",  "TOGGLE",            "true"),
        ],
    ),
    # Чистое исправление бага: включён — значит работает. Настраивать нечего,
    # поэтому ни меню, ни строк, ни группы в настройках.
    dict(
        mod="modW3EERedux_FinisherFix", group=None,
        oldmod="modFinisherFix", oldgroup=None, src="FinisherFix.ws",
        idspace=None, priority=14, menu_key=None,
        title="W3EE Redux - Finisher Fix",
        vars=[],
    ),
]


# ---------------------------------------------------------------------------
#  Подписи. Ключ -> локаль -> текст.
#
#  Разделитель в CSV — вертикальная черта, поэтому её в тексте быть не должно.
#  Диакритика пишется как положено: игра официально локализована на польский,
#  чешский, венгерский и турецкий, все глифы в шрифтах есть.
# ---------------------------------------------------------------------------

TR = {

# Общий корневой пункт. Один на все моды набора.
"w3eeredux_root": {
 "en": "W3EE Redux Add-ons",
 "ru": "Надстройки W3EE Redux",
 "pl": "Dodatki do W3EE Redux",
 "de": "W3EE-Redux-Erweiterungen",
 "fr": "Modules W3EE Redux",
 "es": "Complementos de W3EE Redux",
 "esmx": "Complementos de W3EE Redux",
 "it": "Componenti aggiuntivi W3EE Redux",
 "br": "Complementos do W3EE Redux",
 "cz": "Doplňky pro W3EE Redux",
 "hu": "W3EE Redux kiegészítők",
 "tr": "W3EE Redux Eklentileri",
 "jp": "W3EE Redux アドオン",
 "kr": "W3EE Redux 애드온",
 "cn": "W3EE Redux 扩展",
 "zh": "W3EE Redux 擴充",
 "ar": "إضافات W3EE Redux",
},

"ssht_menu": {
 "en": "Sign Shatter",
 "ru": "Разрыв знаками",
 "pl": "Rozerwanie Znakiem",
 "de": "Zeichen-Zerfetzen",
 "fr": "Éclatement par Signe",
 "es": "Estallido por Signo",
 "esmx": "Estallido por Signo",
 "it": "Frantumazione da Segno",
 "br": "Estilhaçar com Sinal",
 "cz": "Roztrhání Znamením",
 "hu": "Jelrobbantás",
 "tr": "İşaretle Parçalama",
 "jp": "印による粉砕",
 "kr": "표식 산산조각",
 "cn": "法印撕裂",
 "zh": "法印撕裂",
 "ar": "تمزيق بالإشارة",
},

"ssht_humanpoise": {
 "en": "Shatter humans with broken poise",
 "ru": "Разрывать людей со сбитой стойкой",
 "pl": "Rozrywaj ludzi ze złamaną postawą",
 "de": "Menschen mit gebrochener Haltung zerfetzen",
 "fr": "Déchiqueter les humains à l'aplomb brisé",
 "es": "Despedazar humanos con aplomo roto",
 "esmx": "Despedazar humanos con aplomo roto",
 "it": "Fai a pezzi gli umani con equilibrio rotto",
 "br": "Estraçalhar humanos com postura quebrada",
 "cz": "Trhat lidi se zlomeným postojem",
 "hu": "Megtört egyensúlyú emberek szétszaggatása",
 "tr": "Dengesi bozulan insanları parçala",
 "jp": "体勢を崩した人間を粉砕する",
 "kr": "균형이 무너진 인간을 산산조각",
 "cn": "撕裂失去平衡的人类",
 "zh": "撕裂失去平衡的人類",
 "ar": "تمزيق البشر المختل توازنهم",
},

"ssht_humanhp": {
 "en": "   ...only below this health %",
 "ru": "   ...только ниже этого % здоровья",
 "pl": "   ...tylko poniżej tego % zdrowia",
 "de": "   ...nur unterhalb dieses Lebens-%",
 "fr": "   ...seulement sous ce % de santé",
 "es": "   ...solo por debajo de este % de salud",
 "esmx": "   ...solo por debajo de este % de salud",
 "it": "   ...solo sotto questa % di salute",
 "br": "   ...apenas abaixo desta % de vida",
 "cz": "   ...jen pod tímto % zdraví",
 "hu": "   ...csak ezen életerő % alatt",
 "tr": "   ...yalnızca bu can yüzdesinin altında",
 "jp": "   ...この体力%未満のみ",
 "kr": "   ...이 체력 % 미만에서만",
 "cn": "   ...仅在此生命值%以下",
 "zh": "   ...僅在此生命值%以下",
 "ar": "   ...فقط تحت نسبة الصحة هذه",
},

"ssht_shatterscale": {
 "en": "   ...how fast the chance grows with wounds (100 = normal)",
 "ru": "   ...насколько быстро шанс растёт с ранами (100 — обычно)",
 "pl": "   ...jak szybko szansa rośnie z ranami (100 = normalnie)",
 "de": "   ...wie schnell die Chance mit Wunden steigt (100 = normal)",
 "fr": "   ...à quelle vitesse la chance croît avec les blessures (100 = normal)",
 "es": "   ...con qué rapidez crece la probabilidad con las heridas (100 = normal)",
 "esmx": "   ...con qué rapidez crece la probabilidad con las heridas (100 = normal)",
 "it": "   ...quanto in fretta cresce la probabilità con le ferite (100 = normale)",
 "br": "   ...quão rápido a chance cresce com os ferimentos (100 = normal)",
 "cz": "   ...jak rychle šance roste se zraněním (100 = normálně)",
 "hu": "   ...milyen gyorsan nő az esély a sebekkel (100 = normál)",
 "tr": "   ...şans yaralarla ne kadar hızlı artar (100 = normal)",
 "jp": "   ...傷が増えるほど確率が上がる速さ (100 = 標準)",
 "kr": "   ...부상에 따라 확률이 오르는 속도 (100 = 보통)",
 "cn": "   ...概率随伤势增长的速度 (100 = 正常)",
 "zh": "   ...機率隨傷勢增長的速度 (100 = 正常)",
 "ar": "   ...سرعة نمو الفرصة مع الجراح (100 = عادي)",
},

"ssht_killshatter": {
 "en": "Shatter anything Aard kills",
 "ru": "Разрывать всех, кого добил Аард",
 "pl": "Rozrywaj wszystko, co zabije Aard",
 "de": "Alles zerfetzen, was Aard tötet",
 "fr": "Déchiqueter tout ce qu'Aard tue",
 "es": "Despedazar todo lo que mate Aard",
 "esmx": "Despedazar todo lo que mate Aard",
 "it": "Fai a pezzi tutto ciò che uccide Aard",
 "br": "Estraçalhar tudo que Aard matar",
 "cz": "Trhat vše, co zabije Aard",
 "hu": "Szaggasd szét, amit az Aard megöl",
 "tr": "Aard'ın öldürdüğü her şeyi parçala",
 "jp": "アードが倒した敵を粉砕",
 "kr": "아드가 처치한 대상을 산산조각",
 "cn": "撕裂被亚克席杀死的一切",
 "zh": "撕裂被亞克席殺死的一切",
 "ar": "تمزيق كل ما يقتله آرد",
},

"ssht_killshatterhumans": {
 "en": "   ...including humans",
 "ru": "   ...включая людей",
 "pl": "   ...w tym ludzi",
 "de": "   ...auch Menschen",
 "fr": "   ...y compris les humains",
 "es": "   ...incluidos los humanos",
 "esmx": "   ...incluidos los humanos",
 "it": "   ...umani inclusi",
 "br": "   ...incluindo humanos",
 "cz": "   ...včetně lidí",
 "hu": "   ...embereket is",
 "tr": "   ...insanlar dahil",
 "jp": "   ...人間も含む",
 "kr": "   ...인간 포함",
 "cn": "   ...包括人类",
 "zh": "   ...包括人類",
 "ar": "   ...بما في ذلك البشر",
},

"ssht_ignipoise": {
 "en": "Igni shatters humans too",
 "ru": "Игни разрывает людей так же",
 "pl": "Igni też rozrywa ludzi",
 "de": "Igni zerfetzt Menschen ebenso",
 "fr": "Igni déchiquette aussi les humains",
 "es": "Igni también despedaza humanos",
 "esmx": "Igni también despedaza humanos",
 "it": "Anche Igni fa a pezzi gli umani",
 "br": "Igni também estraçalha humanos",
 "cz": "Igni trhá lidi také",
 "hu": "Az Igni is szétszaggatja az embereket",
 "tr": "Igni de insanları parçalar",
 "jp": "イグニも人間を粉砕する",
 "kr": "이그니도 인간을 산산조각",
 "cn": "伊格尼同样撕裂人类",
 "zh": "伊格尼同樣撕裂人類",
 "ar": "إغني يمزق البشر أيضًا",
},

"ssht_ignikill": {
 "en": "Shatter anything Igni kills",
 "ru": "Разрывать всех, кого добил Игни",
 "pl": "Rozrywaj wszystko, co zabije Igni",
 "de": "Alles zerfetzen, was Igni tötet",
 "fr": "Déchiqueter tout ce qu'Igni tue",
 "es": "Despedazar todo lo que mate Igni",
 "esmx": "Despedazar todo lo que mate Igni",
 "it": "Fai a pezzi tutto ciò che uccide Igni",
 "br": "Estraçalhar tudo que Igni matar",
 "cz": "Trhat vše, co zabije Igni",
 "hu": "Szaggasd szét, amit az Igni megöl",
 "tr": "Igni'nin öldürdüğü her şeyi parçala",
 "jp": "イグニが倒した敵を粉砕",
 "kr": "이그니가 처치한 대상을 산산조각",
 "cn": "撕裂被伊格尼杀死的一切",
 "zh": "撕裂被伊格尼殺死的一切",
 "ar": "تمزيق كل ما يقتله إغني",
},

"ssht_burnkill": {
 "en": "Shatter anything burning kills",
 "ru": "Разрывать всех, кто сгорел заживо",
 "pl": "Rozrywaj wszystko, co zabije ogień",
 "de": "Alles zerfetzen, was verbrennt",
 "fr": "Déchiqueter tout ce que le feu tue",
 "es": "Despedazar todo lo que mate el fuego",
 "esmx": "Despedazar todo lo que mate el fuego",
 "it": "Fai a pezzi tutto ciò che uccide il fuoco",
 "br": "Estraçalhar tudo que o fogo matar",
 "cz": "Trhat vše, co upálí oheň",
 "hu": "Szaggasd szét, akit az égés öl meg",
 "tr": "Yanarak ölen her şeyi parçala",
 "jp": "炎上で倒れた敵を粉砕",
 "kr": "화상으로 죽은 대상을 산산조각",
 "cn": "撕裂被灼烧烧死的一切",
 "zh": "撕裂被灼燒燒死的一切",
 "ar": "تمزيق كل ما يقتله الحريق",
},

"ssht_slomochance": {
 "en": "Slow motion chance on shatter",
 "ru": "Шанс замедления времени при разрыве",
 "pl": "Szansa na spowolnienie czasu",
 "de": "Zeitlupen-Chance beim Zerfetzen",
 "fr": "Chance de ralenti lors de l'éclatement",
 "es": "Probabilidad de cámara lenta",
 "esmx": "Probabilidad de cámara lenta",
 "it": "Probabilità di rallentatore",
 "br": "Chance de câmera lenta ao estraçalhar",
 "cz": "Šance na zpomalení času",
 "hu": "Lassítás esélye szétszaggatáskor",
 "tr": "Parçalamada ağır çekim şansı",
 "jp": "粉砕時のスローモーション確率",
 "kr": "산산조각 시 슬로모션 확률",
 "cn": "撕裂时的慢动作概率",
 "zh": "撕裂時的慢動作機率",
 "ar": "فرصة الحركة البطيئة عند التمزيق",
},

"ssht_slomoscale": {
 "en": "   ...strength (lower = stronger)",
 "ru": "   ...сила замедления (меньше = сильнее)",
 "pl": "   ...siła (mniej = mocniej)",
 "de": "   ...Stärke (niedriger = stärker)",
 "fr": "   ...intensité (plus bas = plus fort)",
 "es": "   ...intensidad (menor = más fuerte)",
 "esmx": "   ...intensidad (menor = más fuerte)",
 "it": "   ...intensità (più basso = più forte)",
 "br": "   ...intensidade (menor = mais forte)",
 "cz": "   ...síla (nižší = silnější)",
 "hu": "   ...erősség (kisebb = erősebb)",
 "tr": "   ...güç (düşük = daha güçlü)",
 "jp": "   ...強さ (低いほど強い)",
 "kr": "   ...강도 (낮을수록 강함)",
 "cn": "   ...强度 (越低越强)",
 "zh": "   ...強度 (越低越強)",
 "ar": "   ...القوة (أقل = أقوى)",
},

"ssht_slomotime": {
 "en": "   ...duration, sec",
 "ru": "   ...длительность, сек",
 "pl": "   ...czas trwania, sek",
 "de": "   ...Dauer, Sek.",
 "fr": "   ...durée, sec",
 "es": "   ...duración, seg",
 "esmx": "   ...duración, seg",
 "it": "   ...durata, sec",
 "br": "   ...duração, seg",
 "cz": "   ...trvání, sek",
 "hu": "   ...időtartam, mp",
 "tr": "   ...süre, sn",
 "jp": "   ...継続時間 (秒)",
 "kr": "   ...지속 시간, 초",
 "cn": "   ...持续时间, 秒",
 "zh": "   ...持續時間, 秒",
 "ar": "   ...المدة بالثواني",
},

"dsma_menu": {
 "en": "Dismember Anyone",
 "ru": "Расчленять всех",
 "pl": "Rozczłonkuj Każdego",
 "de": "Jeden zerstückeln",
 "fr": "Démembrer Tout le Monde",
 "es": "Desmembrar a Cualquiera",
 "esmx": "Desmembrar a Cualquiera",
 "it": "Smembra Chiunque",
 "br": "Desmembrar Qualquer Um",
 "cz": "Rozsekat Kohokoli",
 "hu": "Bárkit Feldarabolni",
 "tr": "Herkesi Parçala",
 "jp": "全員を切断可能に",
 "kr": "누구든 절단",
 "cn": "肢解任何人",
 "zh": "肢解任何人",
 "ar": "تقطيع أي شخص",
},

"dsma_armordism": {
 "en": "Dismember armoured humans",
 "ru": "Расчленять бронированных людей",
 "pl": "Rozczłonkuj opancerzonych ludzi",
 "de": "Gepanzerte Menschen zerstückeln",
 "fr": "Démembrer les humains en armure",
 "es": "Desmembrar humanos con armadura",
 "esmx": "Desmembrar humanos con armadura",
 "it": "Smembra gli umani corazzati",
 "br": "Desmembrar humanos blindados",
 "cz": "Rozsekat obrněné lidi",
 "hu": "Páncélos emberek feldarabolása",
 "tr": "Zırhlı insanları parçala",
 "jp": "装甲した人間も切断する",
 "kr": "갑옷 입은 인간도 절단",
 "cn": "肢解身穿铠甲的人类",
 "zh": "肢解身穿鎧甲的人類",
 "ar": "تقطيع البشر المدرعين",
},

"dsma_armorchance": {
 "en": "   ...chance",
 "ru": "   ...шанс",
 "pl": "   ...szansa",
 "de": "   ...Chance",
 "fr": "   ...chance",
 "es": "   ...probabilidad",
 "esmx": "   ...probabilidad",
 "it": "   ...probabilità",
 "br": "   ...chance",
 "cz": "   ...šance",
 "hu": "   ...esély",
 "tr": "   ...şans",
 "jp": "   ...確率",
 "kr": "   ...확률",
 "cn": "   ...概率",
 "zh": "   ...機率",
 "ar": "   ...الفرصة",
},

"fvar_menu": {
 "en": "Finisher Variety",
 "ru": "Разнообразие добиваний",
 "pl": "Różnorodność Wykończeń",
 "de": "Finisher-Vielfalt",
 "fr": "Variété des Achèvements",
 "es": "Variedad de Remates",
 "esmx": "Variedad de Remates",
 "it": "Varietà delle Esecuzioni",
 "br": "Variedade de Execuções",
 "cz": "Rozmanitost Dobíjení",
 "hu": "Kivégzések Változatossága",
 "tr": "Bitiriş Çeşitliliği",
 "jp": "フィニッシュ演出の多様化",
 "kr": "마무리 연출 다양화",
 "cn": "终结动作多样化",
 "zh": "終結動作多樣化",
 "ar": "تنوع الضربات القاضية",
},

"fvar_mode": {
 "en": "Variety: 0 W3EE, 1 vanilla, 2 max",
 "ru": "Разнообразие: 0 W3EE, 1 ваниль, 2 макс",
 "pl": "Różnorodność: 0 W3EE, 1 waniliowa, 2 maks",
 "de": "Vielfalt: 0 W3EE, 1 Vanilla, 2 Max",
 "fr": "Variété: 0 W3EE, 1 vanille, 2 max",
 "es": "Variedad: 0 W3EE, 1 vainilla, 2 máx",
 "esmx": "Variedad: 0 W3EE, 1 vainilla, 2 máx",
 "it": "Varietà: 0 W3EE, 1 vanilla, 2 max",
 "br": "Variedade: 0 W3EE, 1 clássica, 2 máx",
 "cz": "Rozmanitost: 0 W3EE, 1 vanilla, 2 max",
 "hu": "Változatosság: 0 W3EE, 1 eredeti, 2 max",
 "tr": "Çeşitlilik: 0 W3EE, 1 orijinal, 2 maks",
 "jp": "多様性: 0 W3EE, 1 バニラ, 2 最大",
 "kr": "다양성: 0 W3EE, 1 바닐라, 2 최대",
 "cn": "多样性: 0 W3EE, 1 原版, 2 最大",
 "zh": "多樣性: 0 W3EE, 1 原版, 2 最大",
 "ar": "التنوع: 0 W3EE، 1 أصلي، 2 أقصى",
},

"tssb_menu": {
 "en": "Tier-Scaled Set Bonuses",
 "ru": "Сетовые бонусы по тирам",
 "pl": "Bonusy Zestawów wg Poziomu",
 "de": "Set-Boni nach Stufe",
 "fr": "Bonus d'Équipement par Palier",
 "es": "Bonos de Conjunto por Nivel",
 "esmx": "Bonos de Conjunto por Nivel",
 "it": "Bonus Set in Base al Livello",
 "br": "Bônus de Conjunto por Nível",
 "cz": "Bonusy Sad podle Úrovně",
 "hu": "Szintarányos Szett Bónuszok",
 "tr": "Seviyeye Göre Set Bonusları",
 "jp": "ティア連動セットボーナス",
 "kr": "등급 비례 세트 보너스",
 "cn": "按品阶缩放的套装加成",
 "zh": "按品階縮放的套裝加成",
 "ar": "مكافآت الأطقم حسب المستوى",
},

"tssb_enabled": {
 "en": "Grandmaster bonus on every tier",
 "ru": "Гроссмейстерский бонус на всех тирах",
 "pl": "Bonus arcymistrzowski na każdym poziomie",
 "de": "Großmeister-Bonus auf jeder Stufe",
 "fr": "Bonus grand maître à tous les paliers",
 "es": "Bono de gran maestro en todos los niveles",
 "esmx": "Bono de gran maestro en todos los niveles",
 "it": "Bonus da gran maestro a ogni livello",
 "br": "Bônus de grão-mestre em todo nível",
 "cz": "Velmistrovský bonus na všech úrovních",
 "hu": "Nagymesteri bónusz minden szinten",
 "tr": "Her seviyede büyük usta bonusu",
 "jp": "全ティアでグランドマスター効果",
 "kr": "모든 등급에서 그랜드마스터 보너스",
 "cn": "所有品阶均享大师套装加成",
 "zh": "所有品階均享大師套裝加成",
 "ar": "مكافأة الأستاذية في كل المستويات",
},

"tssb_tier1": {
 "en": "   ...strength at tier 1, %",
 "ru": "   ...сила на 1 тире, %",
 "pl": "   ...siła na poziomie 1, %",
 "de": "   ...Stärke auf Stufe 1, %",
 "fr": "   ...puissance au palier 1, %",
 "es": "   ...potencia en nivel 1, %",
 "esmx": "   ...potencia en nivel 1, %",
 "it": "   ...potenza al livello 1, %",
 "br": "   ...força no nível 1, %",
 "cz": "   ...síla na úrovni 1, %",
 "hu": "   ...erő 1. szinten, %",
 "tr": "   ...1. seviyede güç, %",
 "jp": "   ...ティア1の強さ, %",
 "kr": "   ...1등급 강도, %",
 "cn": "   ...品阶 1 强度, %",
 "zh": "   ...品階 1 強度, %",
 "ar": "   ...القوة في المستوى 1، %",
},

"tssb_tier2": {
 "en": "   ...strength at tier 2, %",
 "ru": "   ...сила на 2 тире, %",
 "pl": "   ...siła na poziomie 2, %",
 "de": "   ...Stärke auf Stufe 2, %",
 "fr": "   ...puissance au palier 2, %",
 "es": "   ...potencia en nivel 2, %",
 "esmx": "   ...potencia en nivel 2, %",
 "it": "   ...potenza al livello 2, %",
 "br": "   ...força no nível 2, %",
 "cz": "   ...síla na úrovni 2, %",
 "hu": "   ...erő 2. szinten, %",
 "tr": "   ...2. seviyede güç, %",
 "jp": "   ...ティア2の強さ, %",
 "kr": "   ...2등급 강도, %",
 "cn": "   ...品阶 2 强度, %",
 "zh": "   ...品階 2 強度, %",
 "ar": "   ...القوة في المستوى 2، %",
},

"tssb_tier3": {
 "en": "   ...strength at tier 3, %",
 "ru": "   ...сила на 3 тире, %",
 "pl": "   ...siła na poziomie 3, %",
 "de": "   ...Stärke auf Stufe 3, %",
 "fr": "   ...puissance au palier 3, %",
 "es": "   ...potencia en nivel 3, %",
 "esmx": "   ...potencia en nivel 3, %",
 "it": "   ...potenza al livello 3, %",
 "br": "   ...força no nível 3, %",
 "cz": "   ...síla na úrovni 3, %",
 "hu": "   ...erő 3. szinten, %",
 "tr": "   ...3. seviyede güç, %",
 "jp": "   ...ティア3の強さ, %",
 "kr": "   ...3등급 강도, %",
 "cn": "   ...品阶 3 强度, %",
 "zh": "   ...品階 3 強度, %",
 "ar": "   ...القوة في المستوى 3، %",
},

"tssb_tier4": {
 "en": "   ...strength at tier 4, %",
 "ru": "   ...сила на 4 тире, %",
 "pl": "   ...siła na poziomie 4, %",
 "de": "   ...Stärke auf Stufe 4, %",
 "fr": "   ...puissance au palier 4, %",
 "es": "   ...potencia en nivel 4, %",
 "esmx": "   ...potencia en nivel 4, %",
 "it": "   ...potenza al livello 4, %",
 "br": "   ...força no nível 4, %",
 "cz": "   ...síla na úrovni 4, %",
 "hu": "   ...erő 4. szinten, %",
 "tr": "   ...4. seviyede güç, %",
 "jp": "   ...ティア4の強さ, %",
 "kr": "   ...4등급 강도, %",
 "cn": "   ...品阶 4 强度, %",
 "zh": "   ...品階 4 強度, %",
 "ar": "   ...القوة في المستوى 4، %",
},

"tssb_descgm": {
 "en": "Tooltips: grandmaster value in brackets",
 "ru": "В описании — гроссмейстерское значение в скобках",
 "pl": "W opisie: wartość arcymistrzowska w nawiasie",
 "de": "In Beschreibungen: Großmeisterwert in Klammern",
 "fr": "Descriptions : valeur grand maître entre parenthèses",
 "es": "Descripciones: valor de gran maestro entre paréntesis",
 "esmx": "Descripciones: valor de gran maestro entre paréntesis",
 "it": "Descrizioni: valore da gran maestro tra parentesi",
 "br": "Descrições: valor de grão-mestre entre parênteses",
 "cz": "V popisu: velmistrovská hodnota v závorce",
 "hu": "Leírásban: nagymesteri érték zárójelben",
 "tr": "Açıklamada: büyük usta değeri parantezde",
 "jp": "説明にグランドマスター値を括弧で表示",
 "kr": "설명에 그랜드마스터 수치를 괄호로 표시",
 "cn": "描述中以括号显示大师数值",
 "zh": "描述中以括號顯示大師數值",
 "ar": "في الوصف: قيمة الأستاذية بين قوسين",
},

"tssb_descnote": {
 "en": "Tooltips: add a strength line",
 "ru": "В описании — строка про силу бонуса",
 "pl": "W opisie: wiersz o sile bonusu",
 "de": "In Beschreibungen: Zeile zur Bonusstärke",
 "fr": "Descriptions : ligne sur la puissance du bonus",
 "es": "Descripciones: línea sobre la potencia del bono",
 "esmx": "Descripciones: línea sobre la potencia del bono",
 "it": "Descrizioni: riga sulla potenza del bonus",
 "br": "Descrições: linha sobre a força do bônus",
 "cz": "V popisu: řádek o síle bonusu",
 "hu": "Leírásban: sor a bónusz erejéről",
 "tr": "Açıklamada: bonus gücü satırı",
 "jp": "説明に効果の強さの行を追加",
 "kr": "설명에 보너스 강도 줄 추가",
 "cn": "描述中加入加成强度说明",
 "zh": "描述中加入加成強度說明",
 "ar": "في الوصف: سطر عن قوة المكافأة",
},

"tssb_note": {
 "en": "Tier-scaled strength:",
 "ru": "Сила бонуса по тиру:",
 "pl": "Siła wg poziomu:",
 "de": "Stufenabhängige Stärke:",
 "fr": "Puissance selon le palier :",
 "es": "Potencia según el nivel:",
 "esmx": "Potencia según el nivel:",
 "it": "Potenza in base al livello:",
 "br": "Força conforme o nível:",
 "cz": "Síla podle úrovně:",
 "hu": "Szint szerinti erő:",
 "tr": "Seviyeye göre güç:",
 "jp": "ティアによる強さ:",
 "kr": "등급별 강도:",
 "cn": "按品阶的强度：",
 "zh": "按品階的強度：",
 "ar": "القوة حسب المستوى:",
},

"insc_menu": {
 "en": "Insectoid Mutation Fix",
 "ru": "Починка мутации инсектоида",
 "pl": "Naprawa Mutacji Insektoida",
 "de": "Insektoid-Mutation korrigiert",
 "fr": "Correctif de la Mutation Insectoïde",
 "es": "Arreglo de la Mutación Insectoide",
 "esmx": "Arreglo de la Mutación Insectoide",
 "it": "Correzione Mutazione Insettoide",
 "br": "Correção da Mutação Insetoide",
 "cz": "Oprava Mutace Hmyzáka",
 "hu": "Rovarmutáció javítás",
 "tr": "Böceksi Mutasyon Düzeltmesi",
 "jp": "インセクトイド変異の修正",
 "kr": "곤충형 돌연변이 수정",
 "cn": "虫类突变修正",
 "zh": "蟲類突變修正",
 "ar": "إصلاح طفرة الحشرات",
},

"insc_enabled": {
 "en": "Fix the toxicity exchange rate",
 "ru": "Чинить курс обмена токсичности",
 "pl": "Napraw przelicznik toksyczności",
 "de": "Toxizitäts-Umrechnung korrigieren",
 "fr": "Corriger le taux de conversion de toxicité",
 "es": "Corregir la tasa de conversión de toxicidad",
 "it": "Correggi il tasso di conversione della tossicità",
 "esmx": "Corregir la tasa de conversión de toxicidad",
 "br": "Corrigir a taxa de conversão de toxicidade",
 "cz": "Opravit převod toxicity",
 "hu": "A toxicitás átváltásának javítása",
 "tr": "Toksisite dönüşüm oranını düzelt",
 "jp": "毒性の交換レートを修正",
 "kr": "독성 교환 비율 수정",
 "cn": "修正毒性兑换比率",
 "zh": "修正毒性兌換比率",
 "ar": "إصلاح معدل تحويل السمية",
},

"mutf_combatonly": {
 "en": "Insectoid: only works in combat",
 "ru": "Инсектоид: работает только в бою",
 "pl": "Insektoid: dziala tylko w walce",
 "de": "Insektoid: wirkt nur im Kampf",
 "fr": "Insectoide : actif seulement en combat",
 "es": "Insectoide: solo funciona en combate",
 "esmx": "Insectoide: solo funciona en combate",
 "it": "Insettoide: attivo solo in combattimento",
 "br": "Insetoide: funciona apenas em combate",
 "cz": "Hmyzak: funguje jen v boji",
 "hu": "Rovar: csak harcban mukodik",
 "tr": "Boceksi: sadece savasta calisir",
 "jp": "インセクトイド: 戦闘中のみ有効",
 "kr": "곤충형: 전투 중에만 작동",
 "cn": "虫类: 仅在战斗中生效",
 "zh": "蟲類: 僅在戰鬥中生效",
 "ar": "الحشري: يعمل في القتال فقط",
},

"mutf_adrfloor": {
 "en": "Insectoid: purge speed on an empty Adrenaline bar, %",
 "ru": "Инсектоид: скорость выведения при пустом адреналине, %",
 "pl": "Insektoid: tempo usuwania przy pustej adrenalinie, %",
 "de": "Insektoid: Abbautempo bei leerer Adrenalinleiste, %",
 "fr": "Insectoide : vitesse de purge a adrenaline vide, %",
 "es": "Insectoide: velocidad de purga con adrenalina vacia, %",
 "esmx": "Insectoide: velocidad de purga con adrenalina vacia, %",
 "it": "Insettoide: velocita di rimozione con adrenalina vuota, %",
 "br": "Insetoide: velocidade de remocao com adrenalina vazia, %",
 "cz": "Hmyzak: rychlost odbouravani pri prazdnem adrenalinu, %",
 "hu": "Rovar: meregtelenites ures adrenalinnal, %",
 "tr": "Boceksi: adrenalin bosken toksisite giderme hizi, %",
 "jp": "インセクトイド: アドレナリン空時の解毒速度 (%)",
 "kr": "곤충형: 아드레날린이 비었을 때 해독 속도 (%)",
 "cn": "虫类: 肾上腺素为空时的排毒速度 (%)",
 "zh": "蟲類: 腎上腺素為空時的排毒速度 (%)",
 "ar": "الحشري: سرعة إزالة السمية عند فراغ الأدرينالين ٪",
},

"mutf_adrtop": {
 "en": "Insectoid: purge speed on a full Adrenaline bar, %",
 "ru": "Инсектоид: скорость выведения при полном адреналине, %",
 "pl": "Insektoid: tempo usuwania przy pelnej adrenalinie, %",
 "de": "Insektoid: Abbautempo bei voller Adrenalinleiste, %",
 "fr": "Insectoide : vitesse de purge a adrenaline pleine, %",
 "es": "Insectoide: velocidad de purga con adrenalina llena, %",
 "esmx": "Insectoide: velocidad de purga con adrenalina llena, %",
 "it": "Insettoide: velocita di rimozione con adrenalina piena, %",
 "br": "Insetoide: velocidade de remocao com adrenalina cheia, %",
 "cz": "Hmyzak: rychlost odbouravani pri plnem adrenalinu, %",
 "hu": "Rovar: meregtelenites teli adrenalinnal, %",
 "tr": "Boceksi: adrenalin doluyken toksisite giderme hizi, %",
 "jp": "インセクトイド: アドレナリン満タン時の解毒速度 (%)",
 "kr": "곤충형: 아드레날린이 가득할 때 해독 속도 (%)",
 "cn": "虫类: 肾上腺素满时的排毒速度 (%)",
 "zh": "蟲類: 腎上腺素滿時的排毒速度 (%)",
 "ar": "الحشري: سرعة إزالة السمية عند امتلاء الأدرينالين ٪",
},

"insc_rate": {
 "en": "Insectoid: toxicity burn rate (10 = as coded, 25 = as described)",
 "ru": "Инсектоид: скорость снятия токсичности (10 — как в игре, 25 — как в описании)",
 "pl": "Insektoid: tempo usuwania toksyczności (10 = jak w kodzie, 25 = jak w opisie)",
 "de": "Insektoid: Tempo des Toxizitätsabbaus (10 = wie im Code, 25 = wie beschrieben)",
 "fr": "Insectoïde : vitesse de purge de toxicité (10 = réel, 25 = annoncé)",
 "es": "Insectoide: velocidad de purga de toxicidad (10 = real, 25 = descrito)",
 "esmx": "Insectoide: velocidad de purga de toxicidad (10 = real, 25 = descrito)",
 "it": "Insettoide: velocità di rimozione tossicità (10 = reale, 25 = dichiarato)",
 "br": "Insetoide: velocidade de remoção de toxicidade (10 = real, 25 = descrito)",
 "cz": "Hmyzák: rychlost odbourávání toxicity (10 = skutečnost, 25 = popis)",
 "hu": "Rovar: méregtelenítés sebessége (10 = valós, 25 = leírt)",
 "tr": "Böceksi: toksisite giderme hızı (10 = kodda, 25 = açıklamada)",
 "jp": "インセクトイド: 毒性の除去速度 (10 = 実際, 25 = 説明どおり)",
 "kr": "곤충형: 독성 제거 속도 (10 = 실제, 25 = 설명대로)",
 "cn": "虫类: 毒性清除速度 (10 = 实际, 25 = 描述值)",
 "zh": "蟲類: 毒性清除速度 (10 = 實際, 25 = 描述值)",
 "ar": "الحشري: سرعة إزالة السمية (10 = الفعلي، 25 = الموصوف)",
},

"insc_fixdesc": {
 "en": "Show the real rate in the description",
 "ru": "Показывать настоящий курс в описании",
 "pl": "Pokaż prawdziwy przelicznik w opisie",
 "de": "Echten Wert in der Beschreibung zeigen",
 "fr": "Afficher le vrai taux dans la description",
 "es": "Mostrar la tasa real en la descripción",
 "esmx": "Mostrar la tasa real en la descripción",
 "it": "Mostra il tasso reale nella descrizione",
 "br": "Mostrar a taxa real na descrição",
 "cz": "Zobrazit skutečný převod v popisu",
 "hu": "A valós átváltás mutatása a leírásban",
 "tr": "Gerçek oranı açıklamada göster",
 "jp": "説明に実際のレートを表示",
 "kr": "설명에 실제 비율 표시",
 "cn": "在描述中显示真实比率",
 "zh": "在描述中顯示真實比率",
 "ar": "إظهار المعدل الحقيقي في الوصف",
},

"insc_dmgredon": {
 "en": "Insectoid: restore the removed damage reduction",
 "ru": "Инсектоид: вернуть вырезанное снижение урона",
 "pl": "Insektoid: przywróć usuniętą redukcję obrażeń",
 "de": "Insektoid: entfernte Schadensreduktion zurückholen",
 "fr": "Insectoïde : rétablir la réduction de dégâts supprimée",
 "es": "Insectoide: restaurar la reducción de daño eliminada",
 "esmx": "Insectoide: restaurar la reducción de daño eliminada",
 "it": "Insettoide: ripristina la riduzione danni rimossa",
 "br": "Insetoide: restaurar a redução de dano removida",
 "cz": "Hmyzák: obnovit odstraněné snížení poškození",
 "hu": "Rovar: az eltávolított sebzéscsökkentés visszaállítása",
 "tr": "Böceksi: kaldırılan hasar azaltmayı geri getir",
 "jp": "インセクトイド: 削除されたダメージ軽減を復活",
 "kr": "곤충형: 삭제된 피해 감소 복원",
 "cn": "虫类: 恢复被移除的伤害减免",
 "zh": "蟲類: 恢復被移除的傷害減免",
 "ar": "الحشري: إعادة تقليل الضرر المحذوف",
},

"insc_dmgredperc": {
 "en": "   ...how much weaker repeat hits are, %",
 "ru": "   ...насколько слабее бьют повторные удары, %",
 "pl": "   ...o ile słabsze są kolejne trafienia, %",
 "de": "   ...wie viel schwächer Folgetreffer sind, %",
 "fr": "   ...combien les coups suivants sont plus faibles, %",
 "es": "   ...cuánto más débiles son los golpes seguidos, %",
 "esmx": "   ...cuánto más débiles son los golpes seguidos, %",
 "it": "   ...quanto sono più deboli i colpi successivi, %",
 "br": "   ...quanto mais fracos ficam os golpes seguintes, %",
 "cz": "   ...o kolik slabší jsou další zásahy, %",
 "hu": "   ...mennyivel gyengébbek az ismételt találatok, %",
 "tr": "   ...tekrar eden vuruşlar ne kadar zayıf, %",
 "jp": "   ...連続被弾がどれだけ弱まるか, %",
 "kr": "   ...연속 피격이 얼마나 약해지는지, %",
 "cn": "   ...连续受击减弱多少, %",
 "zh": "   ...連續受擊減弱多少, %",
 "ar": "   ...كم تضعف الضربات المتكررة، %",
},

"insc_dmgredwin": {
 "en": "   ...how many seconds it lasts",
 "ru": "   ...сколько секунд это держится",
 "pl": "   ...ile sekund to trwa",
 "de": "   ...wie viele Sekunden es anhält",
 "fr": "   ...combien de secondes cela dure",
 "es": "   ...cuántos segundos dura",
 "esmx": "   ...cuántos segundos dura",
 "it": "   ...quanti secondi dura",
 "br": "   ...quantos segundos dura",
 "cz": "   ...kolik sekund to trvá",
 "hu": "   ...hány másodpercig tart",
 "tr": "   ...kaç saniye sürer",
 "jp": "   ...何秒間続くか",
 "kr": "   ...몇 초 동안 지속되는지",
 "cn": "   ...持续多少秒",
 "zh": "   ...持續多少秒",
 "ar": "   ...كم ثانية يستمر",
},

"mutf_menu": {
 "en": "Mutation Fixes",
 "ru": "Починка мутаций",
 "pl": "Naprawa Mutacji",
 "de": "Mutations-Korrekturen",
 "fr": "Correctifs des Mutations",
 "es": "Arreglos de Mutaciones",
 "esmx": "Arreglos de Mutaciones",
 "it": "Correzioni alle Mutazioni",
 "br": "Correções de Mutações",
 "cz": "Opravy Mutací",
 "hu": "Mutáció-javítások",
 "tr": "Mutasyon Düzeltmeleri",
 "jp": "変異の修正",
 "kr": "돌연변이 수정",
 "cn": "突变修正",
 "zh": "突變修正",
 "ar": "إصلاحات الطفرات",
},

"mutf_enabled": {
 "en": "Mutation fixes enabled",
 "ru": "Починка мутаций включена",
 "pl": "Naprawy mutacji włączone",
 "de": "Mutations-Korrekturen aktiv",
 "fr": "Correctifs des mutations activés",
 "es": "Arreglos de mutaciones activados",
 "esmx": "Arreglos de mutaciones activados",
 "it": "Correzioni alle mutazioni attive",
 "br": "Correções de mutações ativadas",
 "cz": "Opravy mutací zapnuty",
 "hu": "Mutáció-javítások bekapcsolva",
 "tr": "Mutasyon düzeltmeleri açık",
 "jp": "変異の修正を有効化",
 "kr": "돌연변이 수정 활성화",
 "cn": "启用突变修正",
 "zh": "啟用突變修正",
 "ar": "تفعيل إصلاحات الطفرات",
},

"mutf_fixdesc": {
 "en": "Show real numbers in mutation descriptions",
 "ru": "Показывать в описаниях мутаций настоящие числа",
 "pl": "Pokaż prawdziwe liczby w opisach mutacji",
 "de": "Echte Zahlen in Mutationsbeschreibungen zeigen",
 "fr": "Afficher les vrais chiffres dans les descriptions de mutations",
 "es": "Mostrar cifras reales en las descripciones de mutaciones",
 "esmx": "Mostrar cifras reales en las descripciones de mutaciones",
 "it": "Mostra i valori reali nelle descrizioni delle mutazioni",
 "br": "Mostrar números reais nas descrições das mutações",
 "cz": "Zobrazit skutečná čísla v popisech mutací",
 "hu": "Valós számok a mutációk leírásában",
 "tr": "Mutasyon açıklamalarında gerçek sayıları göster",
 "jp": "変異の説明に実際の数値を表示",
 "kr": "돌연변이 설명에 실제 수치 표시",
 "cn": "在突变描述中显示真实数值",
 "zh": "在突變描述中顯示真實數值",
 "ar": "إظهار الأرقام الحقيقية في أوصاف الطفرات",
},

"mutf_signbypass": {
 "en": "Specter: raise the Sign bonus toward the promised +50% (0 = as in game)",
 "ru": "Призрак: доводить бонус знаков до обещанных +50% (0 — как в игре)",
 "pl": "Zjawa: podnieś premię do Znaków do obiecanych +50% (0 = jak w grze)",
 "de": "Spektral: Zeichen-Bonus auf die versprochenen +50% anheben (0 = wie im Spiel)",
 "fr": "Spectre : porter le bonus de Signes aux +50% promis (0 = tel quel)",
 "es": "Espectro: elevar la bonificación de Signos al +50% prometido (0 = como está)",
 "esmx": "Espectro: elevar la bonificación de Signos al +50% prometido (0 = como está)",
 "it": "Spettro: porta il bonus ai Segni al +50% promesso (0 = come nel gioco)",
 "br": "Espectro: elevar o bônus de Sinais aos +50% prometidos (0 = como está)",
 "cz": "Přízrak: zvýšit bonus ke Znamením na slíbených +50% (0 = jako ve hře)",
 "hu": "Kísértet: a jelbónusz emelése az ígért +50%-ra (0 = ahogy a játékban)",
 "tr": "Hayalet: İşaret bonusunu vaat edilen +50% düzeyine çıkar (0 = oyundaki gibi)",
 "jp": "スペクター: 印の効果を約束の+50%に近づける (0 = ゲームのまま)",
 "kr": "스펙터: 표식 보너스를 약속된 +50%까지 상향 (0 = 게임 그대로)",
 "cn": "幽灵: 将法印加成提升至承诺的 +50% (0 = 保持原样)",
 "zh": "幽靈: 將法印加成提升至承諾的 +50% (0 = 保持原樣)",
 "ar": "الطيف: رفع مكافأة الإشارات إلى +50% الموعودة (0 = كما في اللعبة)",
},

"mutf_sheet": {
 "en": "Character sheet: show Sign Intensity after falloff",
 "ru": "Окно персонажа: показывать мощь знаков с учётом затухания",
 "pl": "Karta postaci: pokaż Moc Znaków po osłabieniu",
 "de": "Charakterbogen: Zeichenintensität nach Abschwächung zeigen",
 "fr": "Fiche de personnage : afficher l'Intensité des Signes après atténuation",
 "es": "Hoja de personaje: mostrar la Intensidad de Signos tras el decaimiento",
 "esmx": "Hoja de personaje: mostrar la Intensidad de Signos tras el decaimiento",
 "it": "Scheda personaggio: mostra l'Intensità dei Segni dopo l'attenuazione",
 "br": "Ficha do personagem: mostrar Intensidade de Sinais após a queda",
 "cz": "Karta postavy: zobrazit Sílu Znamení po útlumu",
 "hu": "Karakterlap: a jelerő mutatása a csökkenés után",
 "tr": "Karakter sayfası: İşaret Gücünü azalma sonrası göster",
 "jp": "キャラクター画面: 減衰後の印の強さを表示",
 "kr": "캐릭터 화면: 감쇠 적용된 표식 강도 표시",
 "cn": "角色面板: 显示衰减后的法印强度",
 "zh": "角色面板: 顯示衰減後的法印強度",
 "ar": "صفحة الشخصية: إظهار قوة الإشارات بعد التضاؤل",
},

"hnum_menu": {
 "en": "Honest Numbers",
 "ru": "Честные числа",
 "pl": "Uczciwe Liczby",
 "de": "Ehrliche Zahlen",
 "fr": "Chiffres Honnêtes",
 "es": "Cifras Honestas",
 "esmx": "Cifras Honestas",
 "it": "Numeri Onesti",
 "br": "Números Honestos",
 "cz": "Poctivá Čísla",
 "hu": "Őszinte Számok",
 "tr": "Dürüst Sayılar",
 "jp": "正直な数値",
 "kr": "정직한 수치",
 "cn": "诚实的数值",
 "zh": "誠實的數值",
 "ar": "أرقام صادقة",
},

"hnum_enabled": {
 "en": "Honest numbers enabled",
 "ru": "Честные числа включены",
 "pl": "Uczciwe liczby włączone",
 "de": "Ehrliche Zahlen aktiv",
 "fr": "Chiffres honnêtes activés",
 "es": "Cifras honestas activadas",
 "esmx": "Cifras honestas activadas",
 "it": "Numeri onesti attivi",
 "br": "Números honestos ativados",
 "cz": "Poctivá čísla zapnuta",
 "hu": "Őszinte számok bekapcsolva",
 "tr": "Dürüst sayılar açık",
 "jp": "正直な数値を有効化",
 "kr": "정직한 수치 활성화",
 "cn": "启用诚实数值",
 "zh": "啟用誠實數值",
 "ar": "تفعيل الأرقام الصادقة",
},

"hnum_signrows": {
 "en": "Sign rows: show what each Sign really fires at",
 "ru": "Строки знаков: показывать, на чём знак бьёт на самом деле",
 "pl": "Wiersze Znaków: pokaż realną moc każdego Znaku",
 "de": "Zeichen-Zeilen: echte Wirkung jedes Zeichens zeigen",
 "fr": "Lignes de Signes : afficher la puissance réelle de chaque Signe",
 "es": "Filas de Signos: mostrar la potencia real de cada Signo",
 "esmx": "Filas de Signos: mostrar la potencia real de cada Signo",
 "it": "Righe dei Segni: mostra la potenza reale di ogni Segno",
 "br": "Linhas de Sinais: mostrar a potência real de cada Sinal",
 "cz": "Řádky Znamení: zobrazit skutečnou sílu každého Znamení",
 "hu": "Jel-sorok: az egyes jelek valós erejének mutatása",
 "tr": "İşaret satırları: her İşaretin gerçek gücünü göster",
 "jp": "印の行: 各印の実際の強さを表示",
 "kr": "표식 항목: 각 표식의 실제 위력 표시",
 "cn": "法印各行: 显示每个法印的真实威力",
 "zh": "法印各行: 顯示每個法印的真實威力",
 "ar": "صفوف الإشارات: إظهار القوة الحقيقية لكل إشارة",
},

"hnum_durability": {
 "en": "Sword damage: count blade wear, as combat does",
 "ru": "Урон мечей: учитывать износ клинка, как в бою",
 "pl": "Obrażenia mieczy: uwzględnij zużycie ostrza, jak w walce",
 "de": "Schwertschaden: Klingenabnutzung einrechnen, wie im Kampf",
 "fr": "Dégâts des épées : compter l'usure de la lame, comme en combat",
 "es": "Daño de espadas: contar el desgaste de la hoja, como en combate",
 "esmx": "Daño de espadas: contar el desgaste de la hoja, como en combate",
 "it": "Danno delle spade: conta l'usura della lama, come in combattimento",
 "br": "Dano das espadas: contar o desgaste da lâmina, como em combate",
 "cz": "Poškození mečů: započítat opotřebení čepele jako v boji",
 "hu": "Kardsebzés: a penge kopásának beszámítása, mint harcban",
 "tr": "Kılıç hasarı: savaştaki gibi bıçak aşınmasını hesaba kat",
 "jp": "剣のダメージ: 戦闘同様に刃の摩耗を反映",
 "kr": "검 피해량: 전투와 동일하게 칼날 마모 반영",
 "cn": "剑伤害: 像战斗中一样计入刀刃磨损",
 "zh": "劍傷害: 像戰鬥中一樣計入刀刃磨損",
 "ar": "ضرر السيوف: احتساب تآكل النصل كما في القتال",
},

"mmpk_menu": {
 "en": "Metamorphosis Picker",
 "ru": "Выбор мутаций Метаморфозы",
 "pl": "Wybór Mutacji Metamorfozy",
 "de": "Metamorphose-Auswahl",
 "fr": "Sélecteur de Métamorphose",
 "es": "Selector de Metamorfosis",
 "esmx": "Selector de Metamorfosis",
 "it": "Selettore Metamorfosi",
 "br": "Seletor de Metamorfose",
 "cz": "Výběr Metamorfózy",
 "hu": "Metamorfózis Választó",
 "tr": "Metamorfoz Seçici",
 "jp": "メタモルフォーゼ選択",
 "kr": "메타모르포시스 선택",
 "cn": "蜕变突变选择器",
 "zh": "蛻變突變選擇器",
 "ar": "محدد التحول",
},

"mmpk_enabled": {
 "en": "Pick mutations in the mutation screen",
 "ru": "Выбирать мутации в экране мутаций",
 "pl": "Wybieraj mutacje na ekranie mutacji",
 "de": "Mutationen im Mutationsbildschirm wählen",
 "fr": "Choisir les mutations dans l'écran des mutations",
 "es": "Elegir mutaciones en la pantalla de mutaciones",
 "esmx": "Elegir mutaciones en la pantalla de mutaciones",
 "it": "Scegli le mutazioni nella schermata mutazioni",
 "br": "Escolher mutações na tela de mutações",
 "cz": "Vybírat mutace na obrazovce mutací",
 "hu": "Mutációk kiválasztása a mutációs képernyőn",
 "tr": "Mutasyonları mutasyon ekranından seç",
 "jp": "変異画面で変異を選択する",
 "kr": "돌연변이 화면에서 돌연변이 선택",
 "cn": "在突变界面中选择突变",
 "zh": "在突變介面中選擇突變",
 "ar": "اختيار الطفرات في شاشة الطفرات",
},


"nhbt_menu": {
 "en": "No Heartbeat",
 "ru": "Без стука сердца",
 "pl": "Bez Bicia Serca",
 "de": "Kein Herzschlag",
 "fr": "Sans Battement de Coeur",
 "es": "Sin Latido",
 "esmx": "Sin Latido",
 "it": "Senza Battito",
 "br": "Sem Batimento",
 "cz": "Bez Tepu Srdce",
 "hu": "Nincs Szívdobogás",
 "tr": "Kalp Atışı Yok",
 "jp": "心音オフ",
 "kr": "심장 박동 끄기",
 "cn": "关闭心跳声",
 "zh": "關閉心跳聲",
 "ar": "بلا دقات قلب",
},

"nhbt_mute": {
 "en": "Silence the low stamina heartbeat",
 "ru": "Отключить стук сердца при низкой выносливости",
 "pl": "Wycisz bicie serca przy niskiej wytrzymałości",
 "de": "Herzschlag bei wenig Ausdauer stummschalten",
 "fr": "Couper le battement de coeur à faible endurance",
 "es": "Silenciar el latido con poca resistencia",
 "esmx": "Silenciar el latido con poca resistencia",
 "it": "Silenzia il battito con poca vigoria",
 "br": "Silenciar o batimento com pouco vigor",
 "cz": "Ztlumit tep srdce při nízké výdrži",
 "hu": "Szívdobogás némítása alacsony állóképességnél",
 "tr": "Düşük dayanıklılıkta kalp atışını sustur",
 "jp": "スタミナ低下時の心音を消す",
 "kr": "기력이 낮을 때 심장 박동 소리 끄기",
 "cn": "关闭低耐力时的心跳声",
 "zh": "關閉低耐力時的心跳聲",
 "ar": "كتم دقات القلب عند انخفاض القدرة",
},

"drgd_menu": {
 "ar": "Dynamic Ragdolls",
 "br": "Dynamic Ragdolls",
 "cn": "Dynamic Ragdolls",
 "cz": "Dynamic Ragdolls",
 "de": "Dynamic Ragdolls",
 "en": "Dynamic Ragdolls",
 "es": "Dynamic Ragdolls",
 "esmx": "Dynamic Ragdolls",
 "fr": "Dynamic Ragdolls",
 "hu": "Dynamic Ragdolls",
 "it": "Dynamic Ragdolls",
 "jp": "Dynamic Ragdolls",
 "kr": "Dynamic Ragdolls",
 "pl": "Dynamic Ragdolls",
 "ru": "Рэгдоллы и смерти",
 "tr": "Dynamic Ragdolls",
 "zh": "Dynamic Ragdolls",
},

"drgd_chance": {
 "ar": "Free ragdoll death chance (%)",
 "br": "Free ragdoll death chance (%)",
 "cn": "Free ragdoll death chance (%)",
 "cz": "Free ragdoll death chance (%)",
 "de": "Free ragdoll death chance (%)",
 "en": "Free ragdoll death chance (%)",
 "es": "Free ragdoll death chance (%)",
 "esmx": "Free ragdoll death chance (%)",
 "fr": "Free ragdoll death chance (%)",
 "hu": "Free ragdoll death chance (%)",
 "it": "Free ragdoll death chance (%)",
 "jp": "Free ragdoll death chance (%)",
 "kr": "Free ragdoll death chance (%)",
 "pl": "Free ragdoll death chance (%)",
 "ru": "Шанс рэгдолл-смерти (%)",
 "tr": "Free ragdoll death chance (%)",
 "zh": "Free ragdoll death chance (%)",
},

"drgd_force": {
 "ar": "Ragdoll impulse strength (%)",
 "br": "Ragdoll impulse strength (%)",
 "cn": "Ragdoll impulse strength (%)",
 "cz": "Ragdoll impulse strength (%)",
 "de": "Ragdoll impulse strength (%)",
 "en": "Ragdoll impulse strength (%)",
 "es": "Ragdoll impulse strength (%)",
 "esmx": "Ragdoll impulse strength (%)",
 "fr": "Ragdoll impulse strength (%)",
 "hu": "Ragdoll impulse strength (%)",
 "it": "Ragdoll impulse strength (%)",
 "jp": "Ragdoll impulse strength (%)",
 "kr": "Ragdoll impulse strength (%)",
 "pl": "Ragdoll impulse strength (%)",
 "ru": "Сила отброса тела (%)",
 "tr": "Ragdoll impulse strength (%)",
 "zh": "Ragdoll impulse strength (%)",
},

"drgd_mute": {
 "ar": "Mute corpses on sign hits",
 "br": "Mute corpses on sign hits",
 "cn": "Mute corpses on sign hits",
 "cz": "Mute corpses on sign hits",
 "de": "Mute corpses on sign hits",
 "en": "Mute corpses on sign hits",
 "es": "Mute corpses on sign hits",
 "esmx": "Mute corpses on sign hits",
 "fr": "Mute corpses on sign hits",
 "hu": "Mute corpses on sign hits",
 "it": "Mute corpses on sign hits",
 "jp": "Mute corpses on sign hits",
 "kr": "Mute corpses on sign hits",
 "pl": "Mute corpses on sign hits",
 "ru": "Тишина трупов при добивании знаками",
 "tr": "Mute corpses on sign hits",
 "zh": "Mute corpses on sign hits",
},

"drgd_drop": {
 "ar": "Drop weapons on non-sword deaths",
 "br": "Drop weapons on non-sword deaths",
 "cn": "Drop weapons on non-sword deaths",
 "cz": "Drop weapons on non-sword deaths",
 "de": "Drop weapons on non-sword deaths",
 "en": "Drop weapons on non-sword deaths",
 "es": "Drop weapons on non-sword deaths",
 "esmx": "Drop weapons on non-sword deaths",
 "fr": "Drop weapons on non-sword deaths",
 "hu": "Drop weapons on non-sword deaths",
 "it": "Drop weapons on non-sword deaths",
 "jp": "Drop weapons on non-sword deaths",
 "kr": "Drop weapons on non-sword deaths",
 "pl": "Drop weapons on non-sword deaths",
 "ru": "Ронять оружие (огонь, яд, бочки)",
 "tr": "Drop weapons on non-sword deaths",
 "zh": "Drop weapons on non-sword deaths",
},

"drgd_deadly": {
 "ar": "Deadly Counter (Mutation 3, low health)",
 "br": "Deadly Counter (Mutation 3, low health)",
 "cn": "Deadly Counter (Mutation 3, low health)",
 "cz": "Deadly Counter (Mutation 3, low health)",
 "de": "Deadly Counter (Mutation 3, low health)",
 "en": "Deadly Counter (Mutation 3, low health)",
 "es": "Deadly Counter (Mutation 3, low health)",
 "esmx": "Deadly Counter (Mutation 3, low health)",
 "fr": "Deadly Counter (Mutation 3, low health)",
 "hu": "Deadly Counter (Mutation 3, low health)",
 "it": "Deadly Counter (Mutation 3, low health)",
 "jp": "Deadly Counter (Mutation 3, low health)",
 "kr": "Deadly Counter (Mutation 3, low health)",
 "pl": "Deadly Counter (Mutation 3, low health)",
 "ru": "Смертельный контрудар (Мутация 3)",
 "tr": "Deadly Counter (Mutation 3, low health)",
 "zh": "Deadly Counter (Mutation 3, low health)",
},

"drgd_fists": {
 "ar": "Fists never dismember",
 "br": "Fists never dismember",
 "cn": "Fists never dismember",
 "cz": "Fists never dismember",
 "de": "Fists never dismember",
 "en": "Fists never dismember",
 "es": "Fists never dismember",
 "esmx": "Fists never dismember",
 "fr": "Fists never dismember",
 "hu": "Fists never dismember",
 "it": "Fists never dismember",
 "jp": "Fists never dismember",
 "kr": "Fists never dismember",
 "pl": "Fists never dismember",
 "ru": "Кулаки не расчленяют",
 "tr": "Fists never dismember",
 "zh": "Fists never dismember",
},


}


def keys_of(m):
    """Ключи подписей мода.

    Общий корневой пункт объявляет КАЖДЫЙ мод со своим id — иначе, поставив
    один мод без остальных, игрок получил бы папку без названия. Текст у всех
    одинаковый, поэтому какая из записей победит при слиянии — неважно.
    """
    if not m["menu_key"]:
        return []
    return ([MENU_ROOT, m["menu_key"]]
            + [v[1] for v in m["vars"]]
            + list(m.get("extra_keys", [])))
